### ISSUE TITLE
Multiple windows build errors

### ISSUE THREAD

**Issue by MigFerreira** [paceholder/nodeeditor#1]
Hi. I'm trying to compile nodes in VS 2015, but I'm getting dozens of compiler errors "error syntax ::" .

I have no idea what is wrong as it seems correct.
Any Idea what it may be?

**Comment by paceholder** [comment]
Hi MigFerreira,

unfortunately, I do not have any windows machine to check it immediately. Could you please paste here the full compilation log? I will try to fix it. If no, I will set-up a virtual machine in a couple of days and make a build.

Thanks for reporting the issue.

**Comment by MigFerreira** [comment]
1>------ Build started: Project: nodes, Configuration: Debug Win32 ------
1>  Connection.cpp
1>D:\Github\nodeeditor\src\Connection.cpp(62): error C2589: ':': illegal token on right side of '::'
1>D:\Github\nodeeditor\src\Connection.cpp(62): error C2059: syntax error: '::'
1>D:\Github\nodeeditor\src\Connection.cpp(67): error C2589: ':': illegal token on right side of '::'
1>D:\Github\nodeeditor\src\Connection.cpp(67): error C2059: syntax error: '::'
1>D:\Github\nodeeditor\src\Connection.cpp(124): error C2589: ':': illegal token on right side of '::'
1>D:\Github\nodeeditor\src\Connection.cpp(124): error C2059: syntax error: '::'
1>D:\Github\nodeeditor\src\Connection.cpp(128): error C2589: ':': illegal token on right side of '::'
1>D:\Github\nodeeditor\src\Connection.cpp(128): error C2059: syntax error: '::'
1>D:\Github\nodeeditor\src\Connection.cpp(151): error C2589: ')': illegal token on right side of '::'
1>D:\Github\nodeeditor\src\Connection.cpp(151): error C2059: syntax error: '::'
1>D:\Github\nodeeditor\src\Connection.cpp(153): error C2181: illegal else without matching if
1>D:\Github\nodeeditor\src\Connection.cpp(198): error C2589: ':': illegal token on right side of '::'
1>D:\Github\nodeeditor\src\Connection.cpp(198): error C2059: syntax error: '::'
1>D:\Github\nodeeditor\src\Connection.cpp(202): error C2589: ':': illegal token on right side of '::'
1>D:\Github\nodeeditor\src\Connection.cpp(202): error C2059: syntax error: '::'
1>D:\Github\nodeeditor\src\Connection.cpp(219): error C2589: ':': illegal token on right side of '::'
1>D:\Github\nodeeditor\src\Connection.cpp(219): error C2059: syntax error: '::'
1>D:\Github\nodeeditor\src\Connection.cpp(223): error C2589: ':': illegal token on right side of '::'
1>D:\Github\nodeeditor\src\Connection.cpp(223): error C2059: syntax error: '::'
1>D:\Github\nodeeditor\src\Connection.cpp(240): error C2589: ')': illegal token on right side of '::'
1>D:\Github\nodeeditor\src\Connection.cpp(240): error C2059: syntax error: '::'
1>D:\Github\nodeeditor\src\Connection.cpp(242): error C2181: illegal else without matching if
1>  ConnectionGeometry.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xlocale(341): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\iosfwd(343): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
1>  ConnectionGraphicsObject.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits(210): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
1>  ConnectionPainter.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\iosfwd(343): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
1>  ConnectionState.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits(210): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
1>  DataModelRegistry.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xstring(2191): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xstring(2178): note: while compiling class template member function 'void std::basic_string<char32_t,std::char_traits<char32_t>,std::allocator<char32_t>>::_Copy(unsigned int,unsigned int)'
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\xstring(2223): note: see reference to function template instantiation 'void std::basic_string<char32_t,std::char_traits<char32_t>,std::allocator<char32_t>>::_Copy(unsigned int,unsigned int)' being compiled
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\string(684): note: see reference to class template instantiation 'std::basic_string<char32_t,std::char_traits<char32_t>,std::allocator<char32_t>>' being compiled
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits(210): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
1>  FlowGraphicsView.cpp
1>d:\github\nodeeditor\src\PortType.hpp(9): error C2059: syntax error: ','
1>d:\github\nodeeditor\src\PortType.hpp(9): error C3805: ',': unexpected token, expected either '}' or a ','
1>d:\github\nodeeditor\src\PortType.hpp(49): error C2589: ':': illegal token on right side of '::'
1>d:\github\nodeeditor\src\PortType.hpp(49): error C2059: syntax error: '::'
1>d:\github\nodeeditor\src\PortType.hpp(50): error C2589: ';': illegal token on right side of '::'
1>d:\github\nodeeditor\src\PortType.hpp(53): error C2589: ':': illegal token on right side of '::'
1>d:\github\nodeeditor\src\PortType.hpp(53): error C2059: syntax error: '::'
1>d:\github\nodeeditor\src\PortType.hpp(54): error C2589: ';': illegal token on right side of '::'
1>  FlowScene.cpp
1>D:\Github\nodeeditor\src\FlowScene.cpp(24): error C2668: 'make_unique': ambiguous call to overloaded function
1>  d:\github\nodeeditor\src\DataModelRegistry.hpp(24): note: could be 'std::unique_ptr<ConnectionGraphicsObject,std::default_delete<_Ty>> make_unique<ConnectionGraphicsObject,FlowScene&,std::shared_ptr<Connection>&>(FlowScene &,std::shared_ptr<Connection> &)'
1>          with
1>          [
1>              _Ty=ConnectionGraphicsObject
1>          ]
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory(1628): note: or       'std::unique_ptr<ConnectionGraphicsObject,std::default_delete<_Ty>> std::make_unique<ConnectionGraphicsObject,FlowScene&,std::shared_ptr<Connection>&>(FlowScene &,std::shared_ptr<Connection> &)' [found using argument-dependent lookup]
1>          with
1>          [
1>              _Ty=ConnectionGraphicsObject
1>          ]
1>  D:\Github\nodeeditor\src\FlowScene.cpp(24): note: while trying to match the argument list '(FlowScene, std::shared_ptr<Connection>)'
1>D:\Github\nodeeditor\src\FlowScene.cpp(27): error C3536: 'cgo': cannot be used before it is initialized
1>D:\Github\nodeeditor\src\FlowScene.cpp(27): error C2664: 'void Connection::setGraphicsObject(std::unique_ptr<ConnectionGraphicsObject,std::default_delete<_Ty>> &&)': cannot convert argument 1 from 'int' to 'std::unique_ptr<ConnectionGraphicsObject,std::default_delete<_Ty>> &&'
1>          with
1>          [
1>              _Ty=ConnectionGraphicsObject
1>          ]
1>  D:\Github\nodeeditor\src\FlowScene.cpp(27): note: Reason: cannot convert from 'int' to 'std::unique_ptr<ConnectionGraphicsObject,std::default_delete<_Ty>>'
1>          with
1>          [
1>              _Ty=ConnectionGraphicsObject
1>          ]
1>  D:\Github\nodeeditor\src\FlowScene.cpp(27): note: No constructor could take the source type, or constructor overload resolution was ambiguous
1>D:\Github\nodeeditor\src\FlowScene.cpp(51): error C2668: 'make_unique': ambiguous call to overloaded function
1>  d:\github\nodeeditor\src\DataModelRegistry.hpp(24): note: could be 'std::unique_ptr<NodeGraphicsObject,std::default_delete<_Ty>> make_unique<NodeGraphicsObject,FlowScene&,std::shared_ptr<Node>&>(FlowScene &,std::shared_ptr<Node> &)'
1>          with
1>          [
1>              _Ty=NodeGraphicsObject
1>          ]
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\memory(1628): note: or       'std::unique_ptr<NodeGraphicsObject,std::default_delete<_Ty>> std::make_unique<NodeGraphicsObject,FlowScene&,std::shared_ptr<Node>&>(FlowScene &,std::shared_ptr<Node> &)' [found using argument-dependent lookup]
1>          with
1>          [
1>              _Ty=NodeGraphicsObject
1>          ]
1>  D:\Github\nodeeditor\src\FlowScene.cpp(51): note: while trying to match the argument list '(FlowScene, std::shared_ptr<Node>)'
1>D:\Github\nodeeditor\src\FlowScene.cpp(53): error C3536: 'ngo': cannot be used before it is initialized
1>D:\Github\nodeeditor\src\FlowScene.cpp(53): error C2664: 'void Node::setGraphicsObject(std::unique_ptr<NodeGraphicsObject,std::default_delete<_Ty>> &&)': cannot convert argument 1 from 'int' to 'std::unique_ptr<NodeGraphicsObject,std::default_delete<_Ty>> &&'
1>          with
1>          [
1>              _Ty=NodeGraphicsObject
1>          ]
1>  D:\Github\nodeeditor\src\FlowScene.cpp(53): note: Reason: cannot convert from 'int' to 'std::unique_ptr<NodeGraphicsObject,std::default_delete<_Ty>>'
1>          with
1>          [
1>              _Ty=NodeGraphicsObject
1>          ]
1>  D:\Github\nodeeditor\src\FlowScene.cpp(53): note: No constructor could take the source type, or constructor overload resolution was ambiguous
1>  Node.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits(210): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
1>  NodeConnectionInteraction.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits(210): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
1>  NodeDataModel.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits(210): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
1>  NodeGeometry.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits(210): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
1>  NodeGraphicsObject.cpp
1>D:\Github\nodeeditor\src\NodeGraphicsObject.cpp(140): error C2589: ')': illegal token on right side of '::'
1>D:\Github\nodeeditor\src\NodeGraphicsObject.cpp(140): error C2059: syntax error: '::'
1>D:\Github\nodeeditor\src\NodeGraphicsObject.cpp(142): error C2589: ')': illegal token on right side of '::'
1>D:\Github\nodeeditor\src\NodeGraphicsObject.cpp(142): error C2059: syntax error: '::'
1>D:\Github\nodeeditor\src\NodeGraphicsObject.cpp(214): error C2589: ')': illegal token on right side of '::'
1>D:\Github\nodeeditor\src\NodeGraphicsObject.cpp(214): error C2059: syntax error: '::'
1>D:\Github\nodeeditor\src\NodeGraphicsObject.cpp(215): error C2589: ')': illegal token on right side of '::'
1>D:\Github\nodeeditor\src\NodeGraphicsObject.cpp(215): error C2059: syntax error: '::'
1>  NodePainter.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits(210): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
1>  NodeState.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vector(723): warning C4530: C++ exception handler used, but unwind semantics are not enabled. Specify /EHsc
1>  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\vector(718): note: while compiling class template member function 'std::vector<std::weak_ptr<Connection>,std::allocator<_Ty>>::vector(unsigned int)'
1>          with
1>          [
1>              _Ty=std::weak_ptr<Connection>
1>          ]
1>  D:\Github\nodeeditor\src\NodeState.cpp(8): note: see reference to function template instantiation 'std::vector<std::weak_ptr<Connection>,std::allocator<_Ty>>::vector(unsigned int)' being compiled
1>          with
1>          [
1>              _Ty=std::weak_ptr<Connection>
1>          ]
1>  d:\github\nodeeditor\src\NodeState.hpp(50): note: see reference to class template instantiation 'std::vector<std::weak_ptr<Connection>,std::allocator<_Ty>>' being compiled
1>          with
1>          [
1>              _Ty=std::weak_ptr<Connection>
1>          ]
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits(210): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
1>  nodes_automoc.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\limits(210): warning C4577: 'noexcept' used with no exception handling mode specified; termination on exception is not guaranteed. Specify /EHsc
1>  Generating Code...
========== Build: 0 succeeded, 1 failed, 1 up-to-date, 0 skipped ==========

**Comment by paceholder** [comment]
Could you please try  to rename everywhere in the code:
```
NONE -> None
IN -> In
OUT -> Out
```

It might be that some macros with such names are defined on Windows.
Please [see the commit](https://github.com/jcelerier/nodeeditor/commit/680db4460574fd366c8dd63cac7043ecc4cc4a64l)

Let me know if that helps.

**Comment by MigFerreira** [comment]
Good catch, That seems to have fixed the issue. Now I´m getting other errors but I can sort through these myself.

Severity	Code	Description	Project	File	Line	Suppression State
Error (active)		more than one instance of function template "make_unique" matches the argument list:	nodes	d:\Github\nodeeditor\src\FlowScene.cpp	24	
Error (active)		more than one instance of function template "make_unique" matches the argument list:	nodes	d:\Github\nodeeditor\src\FlowScene.cpp	51	
Error	C2664	'void Node::setGraphicsObject(std::unique_ptr<NodeGraphicsObject,std::default_delete<_Ty>> &&)': cannot convert argument 1 from 'int' to 'std::unique_ptr<NodeGraphicsObject,std::default_delete<_Ty>> &&'	nodes	D:\Github\nodeeditor\src\FlowScene.cpp	53	
Error	C2664	'void Connection::setGraphicsObject(std::unique_ptr<ConnectionGraphicsObject,std::default_delete<_Ty>> &&)': cannot convert argument 1 from 'int' to 'std::unique_ptr<ConnectionGraphicsObject,std::default_delete<_Ty>> &&'	nodes	D:\Github\nodeeditor\src\FlowScene.cpp	27	
Error	C3536	'ngo': cannot be used before it is initialized	nodes	D:\Github\nodeeditor\src\FlowScene.cpp	53	
Error	C2668	'make_unique': ambiguous call to overloaded function	nodes	D:\Github\nodeeditor\src\FlowScene.cpp	24	
Error	C2668	'make_unique': ambiguous call to overloaded function	nodes	D:\Github\nodeeditor\src\FlowScene.cpp	51	
Error	C3536	'cgo': cannot be used before it is initialized	nodes	D:\Github\nodeeditor\src\FlowScene.cpp	27

**Comment by paceholder** [comment]
I think std::make_unique is implemented as a part of Visual Studio 2015 standard library.
Although, the function is not yet available in gcc's C++11 and I implemented it by myself.

Try to comment this function out in DataModelRegstiry.hpp

**Comment by paceholder** [comment]
I am installing Qt & Visual Studio on Windows.

**Comment by MigFerreira** [comment]
I got it compiling fine, but when I run an example I get a vector exception. 
Haven't had the time to check this issue yet but later today I will have a look at it.

**Comment by paceholder** [comment]
I've got working windows environment. There are lots of windows-related issues in the code. I will fix them soon.

**Comment by paceholder** [comment]
Fixed. Pull the master

**Comment by MigFerreira** [comment]
Great man. Working fine. 
Just had some issues using Qt5 x64 but switched to x86 and everything works fine.

Btw love how you built the DataModelRegistry and how you bind models to it. Great job.

**Comment by paceholder** [comment]
I used x64 Qt libs. 

In my Visual Studio 2015 Community I did not manage to build all three examples at the same time. VS put compiled object files to the same folder and linker was complaining about undefined functions. I need to check CMake settings.

Feel free to contribute if you find some other issues.
Closing this one.
