### ISSUE TITLE
C++14 with CI

### ISSUE THREAD

**Issue by russelltg** [paceholder/nodeeditor#10]
I know you had troubles with travis+newer compilers. 

You should check out https://github.com/mikkeloscar/arch-travis which sets up a archlinux chroot inside the VM. This is useful because arch has really new packages (clang 3.9, g++ 6.2.1) 

That's what I use for chigraph and it's really nice :). 

The builds do take a bit longer (90ish seconds)

**Comment by paceholder** [comment]
I am currently building against different Qt libst (5.4 and 5.6). With clang and gcc I have in total 4 builds

If I use alternative repositories and manually install gcc 5.4 and clang 3.7, I have problems with using the full building matrix. I guess travis' syntax does not allow that.

**Comment by paceholder** [comment]
Used this approach http://genbattle.bitbucket.org/blog/2016/01/17/c++-travis-ci

Just Qt 5.6 is being tested now
