### ISSUE TITLE
Troubles with CMake

### ISSUE THREAD

**Issue by rhingo** [paceholder/nodeeditor#102]
I am new to cmake and am trying to get the calculator example running for the first time.

Here is a step by step of what I did to try to compile and run the example:

1) Within the calculator example directory (Where the `CMakeLists.txt` file is located) I created a subdirectory -> `mkdir build`
2) `cd build`
3) `cmake ..`
4) `make`

After running make I get this error:

```
fatal error: QtCore/QObject: No such file or directory
 #include <QtCore/QObject>
                          ^
compilation terminated.
make[2]: *** [CMakeFiles/calculator.dir/ModuloModel.o] Error 1
make[1]: *** [CMakeFiles/calculator.dir/all] Error 2
make: *** [all] Error 2
```

I am not sure what the right way to go about setting the include paths for the Qt libraries. Any help would be appreciated.

**Comment by russelltg** [comment]
The calculator is a subdirectory of the project, and isn't mean to be built independently of the nodeeditor. 

Build it all together!

From the `nodeeditor` directory, follow those steps:
```
mkdir build
cd build
cmake .. 
make
```

and it should work like a charm (assuming you have Qt installed in one of the default locations)

**Comment by rhingo** [comment]
Oh great that seemed to work, thank you. Do you know how to actually launch the GUI for the calculator example after I finished the make command?

**Comment by russelltg** [comment]
should be `./examples/calculator/calculator` if remember right

**Comment by the-only-ahmed** [comment]
./bin/calculator

**Comment by russelltg** [comment]
aah right thanks. Forgot he had that flag to put binaires in a bin directory 👍

**Comment by rhingo** [comment]
Thank you!
