### ISSUE TITLE
Save Button Doesn't Work

### ISSUE THREAD

**Issue by rhingo** [paceholder/nodeeditor#103]
Does the "Save.." button work for anyone in the Calculator example? I looked at the `main.cpp` in the calculator subdirectory and it seems like `FlowScene::save()` should save the graph in some sort of `.flow` file. Does anyone know whether they are able to save their graphs?

**Comment by paceholder** [comment]
Hi!

It should work. Give me 5 mins

**Comment by paceholder** [comment]
It work on my Linux machine with the `master` branch build.

What is exactly your problem? You press 'save' and nothing happens?

![image](https://user-images.githubusercontent.com/322952/27243440-363a4040-52e2-11e7-81a1-961b8fd152ba.png)

```
{
    "connections": [
        {
            "in_id": "{581959fe-719d-4f40-9334-26fa4809c29b}",
            "in_index": 0,
            "out_id": "{f5230fbb-7a8d-4b11-993a-6f3621e90188}",
            "out_index": 0
        }
    ],
    "nodes": [
        {
            "id": "{f5230fbb-7a8d-4b11-993a-6f3621e90188}",
            "model": {
                "name": "NumberSource",
                "number": "3"
            },
            "position": {
                "x": -385,
                "y": 139
            }
        },
        {
            "id": "{581959fe-719d-4f40-9334-26fa4809c29b}",
            "model": {
                "name": "Result"
            },
            "position": {
                "x": 260,
                "y": 132
            }
        }
    ]
}
```

**Comment by rhingo** [comment]
Yes I don't see the output you are getting above anywhere. I run the executable `./calculator` and then I try creating and saving a graph (by pressing the "Save.." button and then "Activate"). After that it seems like nothing happens (aka no terminal output after pressing the button as well as no file saved anywhere that I can find. Do you know where I should be looking after clicking the save button?

**Comment by paceholder** [comment]
Normally, after pressing the 'save' button you should see the standard system save file dialog. You give the filename and press save. The .flow file is located in the folder where you decided to save it.

**Comment by paceholder** [comment]
Any updates? Can you make a video of your screen?

**Comment by paceholder** [comment]
Please, reopen if there is still the issue
