### ISSUE TITLE
Crash: Attempting to connect an input node into self output node

### ISSUE THREAD

**Issue by MattGuerrette** [paceholder/nodeeditor#111]
There is a crash when attempting to connect nodes to an output node contained on itself. For example doing something like:

![node_editor_crash](https://user-images.githubusercontent.com/6388953/30305232-c045d4a6-973f-11e7-99dc-f950ff81dd4a.png)

Is this expected behavior? I would think that connecting an input node to an output node should be invalid and it should just ignore the attempted connection.

**Comment by paceholder** [comment]
You are right, the crash should not happen and the framework is not intended for making any loops in the graph. I will correct it

**Comment by navyenzo** [comment]
modify the node's compie function

in the compute function don't compute if the output shared pointer equals one of the input shared pointers

problem solved
