### ISSUE TITLE
Message with QT Win64 compiler

### ISSUE THREAD

**Issue by seongnamoh** [paceholder/nodeeditor#119]
Showing some messages such as following with connection_color example; 
how to eliminate the message ?

Undefined value for parameter: ConstructionColor
Undefined value for parameter: NormalColor
Undefined value for parameter: SelectedColor
Undefined value for parameter: SelectedHaloColor
Undefined value for parameter: HoveredColor
Undefined value for parameter: LineWidth
Undefined value for parameter: ConstructionLineWidth
Undefined value for parameter: PointDiameter

**Comment by seongnamoh** [comment]
it happens at this call; the jsonText is empty when the style is initialized with  ConnectionStyle style(jsonText) at the constructor.


ConnectionStyle::ConnectionStyle(QString jsonText)
{
  loadJsonFile(":DefaultStyle.json");
  loadJsonText(jsonText);
}

void ConnectionStyle:: setConnectionStyle(QString jsonText)
{
  ConnectionStyle style(jsonText);

  StyleCollection::setConnectionStyle(style);
}

**Comment by seongnamoh** [comment]
It is not an actually error. ( my debugger couldn't catch it but..it is a kind of informative message coming from this logic if a logic partially change the parameters ).

void
ConnectionStyle::
loadJsonFromByteArray(QByteArray const &byteArray)
{
  QJsonDocument json(QJsonDocument::fromJson(byteArray));

  QJsonObject topLevelObject = json.object();

  QJsonValueRef nodeStyleValues = topLevelObject["ConnectionStyle"];

  QJsonObject obj = nodeStyleValues.toObject();

  CONNECTION_STYLE_READ_COLOR(obj, ConstructionColor);
  CONNECTION_STYLE_READ_COLOR(obj, NormalColor);
  CONNECTION_STYLE_READ_COLOR(obj, SelectedColor);
  CONNECTION_STYLE_READ_COLOR(obj, SelectedHaloColor);
  CONNECTION_STYLE_READ_COLOR(obj, HoveredColor);

  CONNECTION_STYLE_READ_FLOAT(obj, LineWidth);
  CONNECTION_STYLE_READ_FLOAT(obj, ConstructionLineWidth);
  CONNECTION_STYLE_READ_FLOAT(obj, PointDiameter);

  CONNECTION_STYLE_READ_BOOL(obj, UseDataDefinedColors);
}

**Comment by paceholder** [comment]
Hi,

you are right, this is not good.

I put these warning messages under the macro

```
+#ifdef STYLE_DEBUG
+  #define CONNECTION_STYLE_CHECK_UNDEFINED_VALUE(v, variable) { \
+      if (v.type() == QJsonValue::Undefined || \
+          v.type() == QJsonValue::Null) \
+        qWarning() << "Undefined value for parameter:" << #variable; \
+  }
+#else
+  #define CONNECTION_STYLE_CHECK_UNDEFINED_VALUE(v, variable)
+#endif
```

If someone needs to debug a styling problem it is enough to define a `STYLE_DEBUG` environment variable in CMake.

I hope that fixes your issue
