### ISSUE TITLE
Use JSON for serializing the graph

### ISSUE THREAD

**Issue by paceholder** [paceholder/nodeeditor#12]
Binary files are compact but difficult to read without special tools. A structured text document should be a decent solution.

**Comment by hardliner66** [comment]
Best solution would be to support both and let the user decide.

**Comment by paceholder** [comment]
Actually, the solution is simple: Qt's JSON code supports text-based and binary JSON files. You can check it out in the [Qt example](http://doc.qt.io/qt-5/qtcore-json-savegame-example.html).

I want to get rid of my hand-made binary serialization and go for JSON in whatever form the user wants.

**Comment by hardliner66** [comment]
Maybe you could abstract the serialization away so that the user can specify a custom serialization, with QJson as default serializer. This way everybody could plugin the serialization format they want.

**Comment by paceholder** [comment]
Writing the abstracted serialization code is way not trivial. The serialization itself is a complex problem, thus, it is hard to foresee what a client's serialization implementation could look like. For not just the Json serialization is implemented (in its simplest form, without versioning).

**Comment by russelltg** [comment]
Isn't this done?

**Comment by paceholder** [comment]
Well, I made some sort of serializaiton to JSON, there is a way to construct JSON on-the-fly from your data structure and pass to deserialization.
