### ISSUE TITLE
View port window is moving around

### ISSUE THREAD

**Issue by EssenWorkbench** [paceholder/nodeeditor#120]
After creating couple of nodes, if you grab a node with left mouse click(holding) and move around it, the other nodes are also moving around to find a proper position....

it is likely a view port recalculation due to the node moving, but after moving the node couple of times, it doesn't move anymore but, it is randomly moving after zoom in & out opration.

**Comment by seongnamoh** [comment]
workaround was already proposed in the previous issue report.
it can be solved with this simple way : 
    mView->setSceneRect(-32767,-32726,(32727 * 2),(327267 * 2));
