### ISSUE TITLE
start processing on user request

### ISSUE THREAD

**Issue by abdolahsa** [paceholder/nodeeditor#124]
In the examples provided (MathOperationDataModel,...) compute function is called when input port is connected, how can I change them or add custom models to start when user does an action? (e.g clicking on start button, etc.).

**Comment by paceholder** [comment]
You could add some `EnablingDataType` and one extra in-port as a trigger.
Initially you would pass `nullptr` and on the button press pass a valid pointer that would make the input "complete" and release the calculation run.

**Comment by abdolahsa** [comment]
This solution seems to be a hack! Adding one extra port which only checks for start action trigger, confuse our users. can I get the nodes order in a list and call compute action on that order? (suppose I want to read two files frame by frame(8192 bytes), xor-ing them together and showing the result, returning feedback to xor block ...).

**Comment by paceholder** [comment]
Well, if this is a hack then it's a hack from unreal's blueprint editor
![image](https://user-images.githubusercontent.com/322952/31778518-1fe02c4e-b4f1-11e7-8f8a-fac927b22782.png)
Take a look at white connections. As far as I know they are the "trigger" things.

If you don't like an extra data type just pass `nullptr` to outputs until the button is clicked.

Let me know if I did not understand your problem. I'll try to think about it more.

**Comment by abdolahsa** [comment]
What these two function do: iterateOverNodeDataDependentOrder and iterateOverNodeData ? can I get node order by using these functions?

**Comment by russelltg** [comment]
@paceholder, I'm pretty sure your example from UE4 is not what he is looking for.

Imagine you have elaborated the calculator to have some quite complex math taking place, and it takes your computer ~1s to evaluate it. You wouldn't want to take that 1s every time you change a node early on in your chain--imagine typing in a number into an entry field, one digit per second would be awful!

So the thing he wants (If I understand) is to be able to turn off calculation on data change, and instead calculate when an action is triggered (possibly a button or keystroke). 

UE4's blueprint system isn't like this at all--it's a programming langauge and not a flow graph of data.

**Comment by paceholder** [comment]
@russelltg so what is the problem with not triggering the data propagation until the button is pressed? It's up to user model to decide when the data is valid and ready to be shipped.

**Comment by paceholder** [comment]
@abdolahsa I will add an example, sorry, can't do it right now

**Comment by russelltg** [comment]
Ah ok I see now I think you did understand, I just didn't understand your UE4 analogy. 

Just seems hacky, that's all.
