### ISSUE TITLE
checking type converter models in NodeDataModel instead of statically In DataModelRegistry

### ISSUE THREAD

**Issue by abdolahsa** [paceholder/nodeeditor#126]
In DataModelRegistry when we register models we must pass a Boolean to see if it is type converter or not, is it not a better way to add a virtual function in NodeDataModel to manage it? with this approach we can have more flexibility and some extra code will be removed from DataModelRegistry (just check the function) and need not to be checked on compile time:

```
 template<typename ModelType, bool TypeConverter = false>
  void
  registerModel(std::unique_ptr<ModelType> uniqueModel = std::make_unique<ModelType>(), QString const &category = "Nodes")
  {...} 
```

instead add a function to NodeDataModel to check it:

```
class NODE_EDITOR_PUBLIC NodeDataModel
  : public QObject
  , public Serializable
{
  Q_OBJECT

public:

  NodeDataModel();

...
 virtual bool isTypeConverter() { return false;}
...
```

**Comment by russelltg** [comment]
The current implementation is probably faster, due to the type converting nodes being able to to be indexed, reducing finding a type conversion from a O(n) operation to a O(logn) operation. 

I don't see any major benefits to your design, what's your use case?

**Comment by abdolahsa** [comment]
finding a type conversion within small number of operations does not effect performance (there may be at most 1000 types!?) so here performance is not an issue.
suppose I want to create a model  based on NodeDataModel which a user creates it and I created a class to register them all without knowing whether it is a type converter or not!

**Comment by russelltg** [comment]
I'm still confused about your use case--you have to eventually know if it's a converter or not when isTypeConverter is called, so why not just register it?

**Comment by Quincunx271** [comment]
I believe this issue is obsolete after PR #150
