### ISSUE TITLE
qint64 id instead of QString id in NodeData

### ISSUE THREAD

**Issue by abdolahsa** [paceholder/nodeeditor#128]
In class NodeData each node data must have an id which is defined as QString:
```
struct NodeDataType
{
  QString id;
  QString name;
};
```
why you just not using [typeid().hash_code()](http://en.cppreference.com/w/cpp/types/type_info/hash_code) function which returns a unique size_t id?

**Comment by paceholder** [comment]
Because I wasn't aware of that :) Thanks for letting me know.
Could you prepare a corresponding pull-request?

Thanks

Dmitry

**Comment by jcelerier** [comment]
> why you just not using typeid().hash_code() function which returns a unique size_t id?

uh ? hash_code() is not guaranteed to be unique (and in my experience there are common cases where it is not, eg when loading code from plugins in dylibs on macOS).
I think that it would be a bit safer to use something like QUuid : http://doc.qt.io/qt-5/quuid.html

**Comment by russelltg** [comment]
How would the uuid be generated? Ideally it'd be from hashing the string
but I cannot find any such function.

**Comment by jcelerier** [comment]
I guess something like 

    QUuid::createUuidV5(QUuid(), QByteArray(metaobject()->className()));

would work but I don't think it should rely on the type name, since it precludes anyone from introducing a new node with the same name that an existing one (eg in plug-ins, etc). There's also the `uuidgen` command available on windows, mac & linux which generates such an ID.

**Comment by abdolahsa** [comment]
my idea for using hash_code was for preventing users from adding a new NodeData (removing NodeData class) and doing type identification automatically, so if hash_code doesn't work I think using QString from user is a better way.

**Comment by paceholder** [comment]
Taking into account latest commentsб I close this issue.
