### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by miccol** [paceholder/nodeeditor#129]
Hello,
Thank you for your editor. It is really helpful!

I have a doubt about the license. You released the project under the BSD license. However, the project depends on Qt that is under GPL license (https://www1.qt.io/qt-licensing-terms/)

I am not really expert in licensing and, since I am using Qt;s libraries too, I would like to know how did you manage to license under BSD.

Cheers,
Michele

**Comment by paceholder** [comment]
I am not an expert as well. As far as I know, Qt is released under the LGPL license that allows you to link to this libs whatever you want, even proprietary closed source code.

There should be no problems work BSD as long as I don't modify the Qt libs

**Comment by miccol** [comment]
Cool! thanks for clarifying that!

MC
