### ISSUE TITLE
Use JSON-based graphical style settings

### ISSUE THREAD

**Issue by paceholder** [paceholder/nodeeditor#13]
It seems there is no way to make use of [Qt Stylesheets](http://doc.qt.io/qt-5/stylesheet-examples.html) for  setting the colors and linewidths for Nodes and Connections.

I think it would be sufficient to set styles in the form of JSON documents:
```
NodeStyle::setStyle({  "CornerRadius" : 5,
                       "Color" : [ 100, 100, 0 ],
                       "TextColor : [ 255, 255, 255 ],
                       "BorderColor : [ 10, 10, 255 ]
                       "FontSize" : 12
                    });
```

**Comment by jcelerier** [comment]
I do this with the project I work on and it works quite well : 

https://github.com/OSSIA/i-score/blob/master/base/plugins/iscore-plugin-scenario/Scenario/resources/ScenarioColors.json

**Comment by paceholder** [comment]
Demonstration in `examples/styles`
