### ISSUE TITLE
How to code a Flow Control Node in nodeeditor?

### ISSUE THREAD

**Issue by Top61ly** [paceholder/nodeeditor#137]
![looping](https://user-images.githubusercontent.com/12933023/34108792-6a442a54-e43c-11e7-920f-2ddac0be1f7a.png)

This is a image of chigraph. 
I'm trying to make a loop node in my CAD engine. But I have no idea  about that. Could you please show me how to make a flow control node in nodeeditor?

I always have problems of building or installing chigraph...

Thanks!

**Comment by russelltg** [comment]
It's not currently supported in nodeeditor, it's something I've added support for for chigraph (I'm the author). Check out #117 for a real solution.
