### ISSUE TITLE
"Implicit" type conversions

### ISSUE THREAD

**Issue by Quincunx271** [paceholder/nodeeditor#148]
It's a little strange that type conversions are nodes themselves. Some consequences of this are:

* Type conversions show up in the context menu, when the user of an application should never have to worry about it (the conversion node is inserted automatically)
* Diagrams are bigger because of the extra full-fledged node
* Moving nodes around becomes harder, because the full-fledged node isn't moved with the connection

I think it would be useful to have an "implicit" type conversion. These

* Wouldn't show up in the context menu
* Would be part of the connection. Either some kind of label on the connection, or a "node" which is fully part of the connection. The ideal is for this "node" or label to be rather small to reduce clutter.

**Comment by paceholder** [comment]
I totally agree with you. This is quite an ugly design and I realised it too late when a pull-request was already merged. I am looking into it

**Comment by Quincunx271** [comment]
For history, this is addressed by PR #150
