### ISSUE TITLE
Memory leak with FlowScene

### ISSUE THREAD

**Issue by Quincunx271** [paceholder/nodeeditor#151]
Currently, if you aren't careful, it's really easy to leak memory with `FlowScene`. `~FlowScene()` isn't called by default. You have to write `scene->setParent(parentWidget)`, otherwise it's not automatically deleted.

A possible fix would be to modify the constructor of `FlowScene` to something like this:

```c++
  FlowScene(std::shared_ptr<DataModelRegistry> registry =
              std::make_shared<DataModelRegistry>(),
            QWidget* parent = nullptr);
```

```c++
FlowScene::
FlowScene(std::shared_ptr<DataModelRegistry> registry, QWidget* parent)
  : _registry(registry)
{
  setItemIndexMethod(QGraphicsScene::NoIndex);
  setParent(parent);
}
```

**Comment by paceholder** [comment]
@Quincunx271  https://github.com/paceholder/nodeeditor/pull/155
