### ISSUE TITLE
library naming

### ISSUE THREAD

**Issue by Lishen1** [paceholder/nodeeditor#157]
Debug and release build of library have the same name. Usual debug build of library should have SUFFIX **d**. without any difference in naming i forced to put .dll always near my executable, i can`t just add dll to standart search path. Would be good if library will have standart  SUFFIX  and version in the name.

**Comment by paceholder** [comment]
There is an option in `CMakeLists.txt` called `BUILD_DEBUG_POSTFIX_D`.
 It is `off` by default, could be enabled as follows:

`cmake .. -DBUILD_DEBUG_POSTFIX_D=OFF`
