### ISSUE TITLE
Consider using Q_SIGNALS, Q_SLOTS, Q_EMIT, etc

### ISSUE THREAD

**Issue by Quincunx271** [paceholder/nodeeditor#160]
Some C++ libraries out there use the words `signals`, `slots`, etc. as identifiers (e.g. some of Boost). In Qt, these are considered keywords, which makes Qt incompatible with those libraries. However, [Qt lets the user set an option](http://doc.qt.io/qt-5/signalsandslots.html#using-qt-with-3rd-party-signals-and-slots) to decide to turn off the `signals`, `slots`, etc. keywords, and use `Q_SIGNALS`, etc. instead (those macros are always available).

My suggestion is to replace all uses of the Qt keywords with the `Q_KEYWORD` variant, so that users of this library can choose whether they want to set that configuration option.

**Comment by paceholder** [comment]
Merged
