### ISSUE TITLE
Automated Testing

### ISSUE THREAD

**Issue by Quincunx271** [paceholder/nodeeditor#165]
This library currently doesn't have any automated tests (unit tests, integration tests, etc). It has the examples, which function a bit like integration tests in that we can check whether the changes to this library breaks the build for the examples. However, there are no tests that the behavior actually is logical.

The first thing we'd have to decide on is what unit testing library/framework we want to use. QtTest is a thing, but I personally found it somewhat tedious to use. My personal favorite C++ unit testing library is [Catch2](https://github.com/catchorg/Catch2). Note that if you set it up right, you can test the widgets, including signals and the link, using whatever unit testing library (as long as the library allows a custom `main` function).

Adding unit tests would be a rather large endeavor, so I'd recommend adding small pieces at a time. If we decide to do this, it would probably also be a good idea to require future pull requests to have unit tests.

**Comment by paceholder** [comment]
I used Catch2 in [my other projects](https://github.com/paceholder/component-manager/tree/master/tests).

I wasn't sure about GUI testing. But if you say it is possible, I'll give it a try ;)

**Comment by Quincunx271** [comment]
So here's something I've found: in order to test some GUI aspects, you have to make a `QApplication`. Unfortunately, this doesn't work with Travis AFAIK, since Travis doesn't have a GUI to connect to. The alternative I've found is to use `QCoreApplication`, but if you use that, you'll get segfaults when you try to use unsupported operations.

Testing with `QApplication` works just fine on my machine, but not on Travis.

**Comment by paceholder** [comment]
I think we can close it as some tests were implemented. Thanks for your help.
