### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Quincunx271** [paceholder/nodeeditor#166]
We could use some documentation. The examples certainly help, but I found that once I started trying to do more complex things, I ended up having to dig into the source code to understand how to use this library.

GitHub has a feature where each repository can have a website. Maybe we could set up the documentation there? Or maybe we could use GitHub's wiki feature?

**Comment by paceholder** [comment]
At work I used to write a decent documentation within the doxygen environment.

The key trick is to use large plane **markdown** files as if it were a book or an article.
doxygen is capable of including the markdown documents into its generated html pages.

So I simply write a small article on any sub-component and link it to the main landing page (index.html)

Another benefit is that we could reference the documentation from the `README.md` file.

**Comment by paceholder** [comment]
https://qtnodes.readthedocs.io/en/latest/
This is the first shot, I'll update and extend it as needed or requested
