### ISSUE TITLE
no Save Button available

### ISSUE THREAD

**Issue by yoiang** [paceholder/nodeeditor#179]
Hello!
I'm excited to try out Node Editor on a project! While testing out the examples in MacOS, including the calculator, it sounds like there should be a Save Button available to save the current node arrangement. However in all examples there is no interface available besides the right click node menu!

Let me know if there is any additional information I can provide to help understand the problem. 

MacOS 10.13.4
Qt 5.11.0

**Comment by paceholder** [comment]
Hi,

sorry for maybe a stupid question. Isn't the menu available on the top of the screen?

I'll check it in the evening, I need to setup the dev environmen on my mac (I use Linux most of the time).

Maybe this one is relevant: https://stackoverflow.com/questions/25261760/menubar-not-showing-for-simple-qmainwindow-code-qt-creator-mac-os

Thanks

Dmitry

**Comment by yoiang** [comment]
No worries! Unfortunately there are no menu options available besides the system menu.

I'll have to poke some of the suggestions in the Stack link, thanks :D

**Comment by paceholder** [comment]
Better late than never. I have a mac now and the issue was fixed. The system menu on Mac was build a bit differenly compared to Linux and Windows. Both actions for "save" and "load" neede a single "root" menu called "File" (for example).
