### ISSUE TITLE
DataModel constructor with parameters

### ISSUE THREAD

**Issue by jetrus** [paceholder/nodeeditor#180]
Hello.

I have a few files. Each has parameters (different number of inputs). I want to add them as different models using a single DataModel class.
For this, passing the parameters to the constructor. Is it possible?

for example

Int number_of_in[4] ={3,2,5,1};

auto ret = std::make_shared<DataModelRegistry>();

for(int i=0;i<4;++I)
  ret->registerModel<MyDataModel(number_of_in[i])>("Sources");

Thank you.

**Comment by Quincunx271** [comment]
Yes, you can do this. Just pass in a lambda that works for what you want to do:

```c++
int values[4] = {3, 2, 5, 1};

auto ret = std::make_shared<DataModelRegistry>();

for (int value : values) {
    ret->registerModel<MyDataModel>("Sources",
        [value] { return std::make_unique<MyDataModel>(value); });
}
```

**Comment by jetrus** [comment]
@Quincunx271 Thank you very much, it works.
