### ISSUE TITLE
Different color for connection

### ISSUE THREAD

**Issue by jetrus** [paceholder/nodeeditor#184]
Hi guys!

In the example connection_colors, we set "UseDataDefinedColors": true.
where and how to set colors for typeData?

I saw (Diffenent colors for different NodeDataTypes # 19) but did not understand.
Sorry if the question is stupid

**Comment by paceholder** [comment]
Hi

Your question is perfectly valid. The current implementation is stupid. I
take the name of a data type, find a hash value of its name, and then cast
to 6 bytes color. So a unique color is defined automatically in a stupid
and obscure manner.

I need to add a feature for some really user/data defined colors. And of
course, finally write some documentation.

Regards,

Dmitry

**Comment by jetrus** [comment]
@paceholder 
I just did not understand exactly where to use Qhash. Overload in my class MyNodeData or setConnectionStyle(). Сan be an example code? In  example "connection_colors" the colors are blue and purple, but I do not see the code that sets this. Sorry, I'm stupid in this question)).

**Comment by jetrus** [comment]
I solved this problem by adding the parameter QColor to the NodeDataType structure.
`struct NodeDataType
{
  QString id;
  QString name;
  QColor  color;
};`

and changing the code where the color is set via NodeDataType.id
