### ISSUE TITLE
Error: can not connect input to output

### ISSUE THREAD

**Issue by jetrus** [paceholder/nodeeditor#186]
After the commit Prefer for loop over lambda (#181)
I can not connect the input of the Nodes with the output of another Nodes. 
And only connect the output ->  input
variant first output -> input - works:
![1](https://user-images.githubusercontent.com/39768264/41152246-c219aeb4-6b1b-11e8-83f6-e3e25cf8d0b6.png)
variant second output -> input does not work now:
![2](https://user-images.githubusercontent.com/39768264/41152527-866ad45a-6b1c-11e8-9eff-8e8bcfd26699.png)

Thanks,
regards jetru.

**Comment by facontidavide** [comment]
I can not access a computer until Monday, sorry. It is not happening to me and I don't know how to reproduce it

**Comment by jetrus** [comment]
@paceholder @facontidavide sorry maybe it was before this commit
May 28, it worked, only today drew attention to what does not work
I will study this problem

**Comment by facontidavide** [comment]
Please revert one commit at a time to see when it was introduced. Cheers

**Comment by jetrus** [comment]
@facontidavide sorry, in commit "Commits on May 29, 2018" already no work
I will try next

**Comment by paceholder** [comment]
Please open another issue if there is some problems.
