### ISSUE TITLE
Suggestion: Steal NodeDataModel when removing a Node from a FlowScene 

### ISSUE THREAD

**Issue by LaurentNovac** [paceholder/nodeeditor#188]
Hi ! and congrats for this useful library i've been using for a few days !

Here is my suggestion / question
Maybe i'm missing something here:

QtNodes::Node is the owner of QtNodes::NodeDataModel which is perfect
```
  Node&createNode(std::unique_ptr<NodeDataModel> && dataModel);
  Node(std::unique_ptr<NodeDataModel> && dataModel);
```
My use case is that i'm implementing Macro patches such as you can see in Quartz composer. So i need to "move" nodes between scenes. 

I would then like to steal the model from a Node in a safe way, when i know it will no longer be used.
My suggestion is that:

`  void FlowScene::removeNode(Node& node);
`

become 

`std::unique_ptr<NodeDataModel> FlowScene::removeNode(Node& node);`

which means that before completely destroying the Node it would move it's model, which is safe as the Node will be destroyed.

I hope this make sense and if not could you please point me to a better solution ? Otherwise i would gladly do a PR.

**Comment by paceholder** [comment]
I think this must be pretty much doable now because I split view from scene and scene from grah model.
