### ISSUE TITLE
Diffenent colors for different NodeDataTypes

### ISSUE THREAD

**Issue by russelltg** [paceholder/nodeeditor#19]
So a useful feature to me would be diffenent colors for different `NodeDataType`s to make different types easily differentiated. 

This kind of goes against the styling you recently implemented, but there are a few ways around that. 

## Approach 1
Have a `QColor` member in `NodeDataType` and just use that for rendering. It might be nice to have different colors for hover, select etc or just they are made lighter for hover etc. 

## Approach 2 
A style theme defines a bunch of possible colors that could be used for connections, based on the color scheme they are going for, then they are assigned to be different for different data types.

## Conclusion
I personally like approach 2 better because it follows color schemes and doesn't need each `NodeDataType` to define all their own custom colors, it just works and it looks good but you can't like assign red to a specific data type (which isn't really a loss IMHO because that would break color scheming anyways). 

I'm willing to write the code for it :).

**Comment by paceholder** [comment]
I had further style development in mind. What we have now is kind of a first draft. I was thinking of a Style member (non-static) that could override the global (static) one.

If you have something working in your project I would be glad to see some cool screenshots ( and maybe steal one for the README section). Of course, I can checkout your code, but then it would require some time to understand what is going on there ;-)

**Comment by paceholder** [comment]
Wait, I read your text one more time. Did you see the current styles implementation from a couple of days ago?

**Comment by russelltg** [comment]
I don't have anything working yet, I was curious how you wanted it done
before I started work.

I'll start tonight :).

**Comment by paceholder** [comment]
I meant the nearest future (if you have == when you have)

**Comment by russelltg** [comment]
It's not exactly at the top of my priorities right now, I realize. There are other enhancements I need first, but it will probably be in the next weekish.

**Comment by v0q** [comment]
I had actually added this to my project as I was needing it as well, basically using the Approach 1 that russelltg has suggested. Helps identify which nodes can be connected. I'll try and update the editor files on my git soonish. Got only Qt5.7 at the university and CMake and Qt5.7 fail to use C++14 flags at compile time (explained here https://bugreports.qt.io/browse/QTBUG-53002) so might be a while.

The thing is that as the node editor's been modified on my end prior to the latest release, I'm still using the old one.

![image](https://cloud.githubusercontent.com/assets/1763369/20797725/f86891e4-b7d3-11e6-9222-04730bf68e01.png)

**Comment by paceholder** [comment]
Guys, I am stupid (or just inattentive). I just got what @russelltg meant with different colors for different `NodeDataTypes`. I was thinking all the time about different Styles for different Nodes.

Thus, 
### Approach 3

1. take the hash from NodeDataType::id
2. map it to the range 0x080808 - 0xFFFFFF
(we use the upper half of 0x00-0xFF range to get brighter colors, visible on the dark theme)
3. build color from this number - 0xABBC99 -> (AB, BC, 99)

**Comment by paceholder** [comment]
"Fast and dirty" test 

![image](https://cloud.githubusercontent.com/assets/322952/20800356/8c025f82-b7e5-11e6-8f8a-5686f6c1aee9.png)

**Comment by russelltg** [comment]
Yeah sorry I could have been more clear :/. 

It's also important that the ports are colored too, I can PR it when I get home from school :)

**Comment by paceholder** [comment]
You might want to check my PR and maybe use it as a starting point

**Comment by russelltg** [comment]
Yeah I saw that does it work to pr into your pr branch to update your pr?
It should....

**Comment by paceholder** [comment]
Implemented. There is an example `connection_colors`
