### ISSUE TITLE
Possibilities for full-duplex ports (i.e. topology map).

### ISSUE THREAD

**Issue by Broekman** [paceholder/nodeeditor#190]
First of all thanks for this library!

It's probably not really within the scope of this project but would it be a lot of work to add duplex ports/connections? An example (a.k.a. what I need) would be where a node represents a network device with full-duplex ports (e.g. switch) which can be interconnected to each other. In other words, building a physical network topology. Thanks in advance!

**Comment by russelltg** [comment]
Would be totally possible if #117 were to be merged

**Comment by Broekman** [comment]
Thanks Russel, I'm going to pull in the changes from that PR and try it out. Closing this for now.

**Comment by Broekman** [comment]
In that case, let's leave it open for a moment longer.

**Comment by Broekman** [comment]
@russelltg, would you mind giving me a push into the right direction (using your PR). Only if you have the time of course.

Say I have a list of network devices (i.e. nodes) that each contain one or more local interfaces (i.e. ports). These ports could have an interconnection to a port on another device. I would like to iterate over the list of devices and create a custom node with x ports each having a unique identifier.

I've already managed to create the devices (i.e. nodes) but I'm struggling on creating the custom ports for each device.

Many thanks in advance.

**Comment by russelltg** [comment]
How my PR works is it entirely separates the representation of the underlying data from the graph itsself.

Basicly, don't use `DataFlowScene`, use `FlowScene` directly and subclass `FlowSceneModel` with your own data representation.

**Comment by Broekman** [comment]
Managed to get this to work a while back with some custom edit to the original master branch. Thanks.
