### ISSUE TITLE
Is there an easy way to get click or keypress events

### ISSUE THREAD

**Issue by circuitsforfun** [paceholder/nodeeditor#195]
Is there an easy way to get mouse clicks or keypress events either at the NodeDataModel level or from the flowscene and then iterate over which nodes are currently selected?
I've tried adding event and eventfilter overrides at the NodeDataModel level but don't get button or keypress events unless I add a widget to the node and install an event filter to the widget which I don't want. I want it to trigger an event no matter where you click on the node and not just within the widget region. or if I can capture global keypress events and iterate over the entire node graph and determine which nodes were currently selected that might work for my use case.

Any ideas on how I can implement that without digging deeper into the framework code?
Ideally if I can implement it in my nodes or in the main function that would be best.

**Comment by fredakilla** [comment]
You could derivate FlowScene with your own class and override the keyPressEvent method.
You will get access to nodes list inside your class.
Check my code, if you want an example, it works fine:
https://github.com/fredakilla/spkgen/blob/master/src/CustomFlowScene.h

**Comment by circuitsforfun** [comment]
Yea that looks like a good workaround, thanks!

**Comment by Daguerreo** [comment]
> You could derivate FlowScene with your own class and override the keyPressEvent method.
> You will get access to nodes list inside your class.
> Check my code, if you want an example, it works fine:
> https://github.com/fredakilla/spkgen/blob/master/src/CustomFlowScene.h

Since the post is still useful, the up-to-date link to the header is this:
https://github.com/fredakilla/spkgen/blob/master/src/node-editor/common/CustomFlowScene.h
