### ISSUE TITLE
Models invisible under Mac OS X Mojave in Dark Mode

### ISSUE THREAD

**Issue by andrewssobral** [paceholder/nodeeditor#197]
Hi @paceholder , many thanks for this great project!
Just an small issue found on Mac OS X in Dark Mode, the items are invisible:

<a href="https://ibb.co/gPyEvf"><img src="https://preview.ibb.co/fjfio0/Screen-Shot-2018-10-20-at-02-06-59.png" alt="Screen-Shot-2018-10-20-at-02-06-59" border="0"></a>

I tried to search a solution over Internet, but it is not clear if this is a Qt or Mac issue (https://bugreports.qt.io/browse/QTBUG-68850), or something that we can modify in the nodeeditor FlowScene.

This is my Qt environment:

<a href="https://ibb.co/kg4jT0"><img src="https://preview.ibb.co/m6wL1L/Screen-Shot-2018-10-20-at-02-18-13.png" alt="Screen-Shot-2018-10-20-at-02-18-13" border="0"></a>

**Comment by fredakilla** [comment]
I'm on linux, and I experienced bugs with the Qt 5.11.2 like QFileDialog invisible too (no way to load or save file). However items were visible for me... Maybe, try 5.11.1, works fine with my project using nodeeditor.

**Comment by sindney** [comment]
It's the font color is white in dark mode, i guess it's qt's responsibility to support osx's dark mode, for now i'd recommend you to use a custom qt stylesheet, like this one: https://github.com/ColinDuquesnoy/QDarkStyleSheet

**Comment by andrewssobral** [comment]
Thank you so much @sindney , now it's looking great  👍 
<a href="https://ibb.co/gXYc8V"><img src="https://preview.ibb.co/fsE62q/Screen-Shot-2018-11-07-at-22-29-37.png" alt="Screen-Shot-2018-11-07-at-22-29-37" border="0"></a>
I just did the steps described here: 
https://github.com/ColinDuquesnoy/QDarkStyleSheet#c
