### ISSUE TITLE
get trees in the scene and run each in separate threads

### ISSUE THREAD

**Issue by jaafari** [paceholder/nodeeditor#201]
How can we get trees in the scene? 
There is a method for iterating over NodeDataModels (iterateOverNodeDataDependentOrder) but this function iterates over all nodes, I want a method to iterate over each tree, and it must see each node toward flow direction.
 I've written a subclass of NodeDataModel with virtual method process, to add a process to each node. I want to separate each tree and run them in separate threads.

```
class RunnableDataModel: public NodeDataModel
{
  virtual void preprocess();
  virtual int process() = 0;
  virtual void postprocess();
...
}
```

**Comment by paceholder** [comment]
In the latest master (v3) it is possle to call the functions of the `AbstractModelGraph` class and traverse the whole graph.

https://qtnodes.readthedocs.io/en/master/classes.html#_CPPv4N7QtNodes18AbstractGraphModelE

see functions `allNodeIds` and `connections(NodeId, PortType, PortIndex)`
