### ISSUE TITLE
Screenshots gallery

### ISSUE THREAD

**Issue by fredakilla** [paceholder/nodeeditor#202]
Thanks for nodeeditor it's a great library. 
Here my curent project that use nodeeditor, a particles editor for games.
![image](https://i.imgur.com/9oEWdjl.png)

**Comment by paceholder** [comment]
Thanks a lot for your feedback and for sharing a screenshot. 

Can I add the link to your project to README ? https://github.com/fredakilla/spkgen

**Comment by fredakilla** [comment]
Yes with pleasure, thanks

**Comment by paceholder** [comment]
Done! Thank you
