### ISSUE TITLE
Example with just the Graphics part ?

### ISSUE THREAD

**Issue by Buanderie** [paceholder/nodeeditor#203]
Hello,
I was wondering if it would be easy to use the code just for the rendering part. No computation, event, or input/output type management, etc.
As a matter of fact I have my own processing graph library and with no GUI and just wanted to use a graphical editor to add/delete nodes and links.
Would it be possible to add an example with just the node/link rendering alone ? Or is it just not possible just to use the rendering part ?

Thank you.

**Comment by paceholder** [comment]
Hi,

You could write one empty dummy model and one dummy datatype. And write absolutely no data processing code. This would take up 20 lines of code.
The rest should work -- you will be able to connect everything to everything. I can elaborate on that in a couple of days. 

Best,

Dmitry

**Comment by Buanderie** [comment]
Well, thank you for answering. 
I haven't even considered this solution in the first place :smile: 

Great project, btw.
