### ISSUE TITLE
QApplication: no such file or director

### ISSUE THREAD

**Issue by sergerold** [paceholder/nodeeditor#206]
Hi

I'm trying to build the connection_colors example. The project configures fine when running cmake file from QtCreator but when trying to build it gives the following error:

"C:\Users\Documents\dev\nodeeditor-master\examples\connection_colors\main.cpp:1: error: QtWidgets/QApplication: No such file or directory
 #include <QtWidgets/QApplication>"

Any ideas on how to fix this? 

Thanks

**Comment by maxwell-lau** [comment]
if you use .pro,you can add QT+=gui.

**Comment by paceholder** [comment]
Hi!

Sorry for a late answer. Did you manage to resolve the issue?

This message usually means that you are not linking the QtGui library in your project.

Dmitry

**Comment by paceholder** [comment]
Please reopen if it is still relevant.

Regards,

Dmitry
