### ISSUE TITLE
Make an example showing the use of signal dataInvalidated()

### ISSUE THREAD

**Issue by Daguerreo** [paceholder/nodeeditor#214]
as from subject

**Comment by paceholder** [comment]
Commit: 6aeec6c7b2d847a616a8506083a7c45933f83ad6

See file `examples/calculator/NumberSourceDataModel.cpp`,
function `void NumberSourceDataModel::onTextEdited(QString const & string)`

File: `src/Node.cpp`,
 function `void Node::onDataInvalidated(PortIndex index)`
