### ISSUE TITLE
Converter issue in calculator example

### ISSUE THREAD

**Issue by Daguerreo** [paceholder/nodeeditor#217]
Consider this graph:

![screen01](https://user-images.githubusercontent.com/6747152/54267931-7606e200-457a-11e9-803a-5cd701307c37.png)

Then remove the output connection from **Module** block:

![screen02](https://user-images.githubusercontent.com/6747152/54267932-769f7880-457a-11e9-9bdf-2797bc199580.png)

Other blocks are still holding a result while should be resetted. It happens only when conversion connections are involved beacuse the converters hold a copy of the shared pointer:

```
std::shared_ptr<NodeData>
DecimalToIntegerConverter::
operator()(std::shared_ptr<NodeData> data)
{
  auto numberData =
    std::dynamic_pointer_cast<DecimalData>(data);

  if (numberData)
  {
    _integer = std::make_shared<IntegerData>(numberData->number());
  }

  return _integer;
}


std::shared_ptr<NodeData>
IntegerToDecimalConverter::
operator()(std::shared_ptr<NodeData> data)
{
  auto numberData =
    std::dynamic_pointer_cast<IntegerData>(data);

  if (numberData)
  {
    _decimal = std::make_shared<DecimalData>(numberData->number());
  }

  return _decimal;
}
```

changing those to: 

```
std::shared_ptr<NodeData>
DecimalToIntegerConverter::
operator()(std::shared_ptr<NodeData> data)
{
  auto numberData =
    std::dynamic_pointer_cast<DecimalData>(data);

  if (numberData)
  {
    _integer = std::make_shared<IntegerData>(numberData->number());
  }
  else
  {
    _integer.reset();
  }

  return _integer;
}


std::shared_ptr<NodeData>
IntegerToDecimalConverter::
operator()(std::shared_ptr<NodeData> data)
{
  auto numberData =
    std::dynamic_pointer_cast<IntegerData>(data);

  if (numberData)
  {
    _decimal = std::make_shared<DecimalData>(numberData->number());
  }
  else
  {
    _decimal.reset();
  }

  return _decimal;
}
```

Fix the issue. 
Don't know if it's the better implementation for that though.

**Comment by paceholder** [comment]
Thank you, I did not notice that earlier

**Comment by Daguerreo** [comment]
> Thank you, I did not notice that earlier

By the way @paceholder , the copy of the shared pointer is really necessary since we're just check if it's a valid cast? Shouldn't a const reference be enough?
