### ISSUE TITLE
Suggestion: provide notify method to wrap Q_EMIT

### ISSUE THREAD

**Issue by Daguerreo** [paceholder/nodeeditor#218]
Providing an additional wrapper method of signal emission like:

   void notifyDataUpdated(PortIndex port){
      Q_EMIT dataUpdated(port);
   }

for simple blocks avoid to make the Q_OBJECT macro for every block, resulting in minor object size and compilation time, due to the non-generation of che moc_XXX.o

**Comment by paceholder** [comment]
Could you please clarify on object size and compilation time?

As far as I know, Q_EMIT is defined as `# define Q_EMIT` (i.e. no real extra code) and only the Q_OBJECT macro defines if the moc proccessing takes place.

**Comment by Daguerreo** [comment]
> Could you please clarify on object size and compilation time?
> 
> As far as I know, Q_EMIT is defined as `# define Q_EMIT` (i.e. no real extra code) and only the Q_OBJECT macro defines if the moc proccessing takes place.

Actually, you're right. My mistake sorry
