### ISSUE TITLE
NodeDataType subtypes

### ISSUE THREAD

**Issue by kervel** [paceholder/nodeeditor#219]
Hello, i'm trying to use nodeeditor for a image processing flow. i have processing blocks that can work on both color images and grayscale images, but also image processing blocks that can only work on grayscale images.

 So i'd like to have some kind of subtyping in NodeDataType. i guess implementing would be doable, any hints ? (i'd think changing the sameType function to a isAssignableFrom function, but not sure where to put the logic then)

Thanks,
Frank

**Comment by paceholder** [comment]
Hi Frank,

maybe you'd like to use converters?
Take a look at the `examples/calculator`. In this example some nodes are able to work with two data types: `DecimalData` and `IntegerData`. 
We register two converters that are able to change the data type "on the fly".
Consider a graph:

![image](https://user-images.githubusercontent.com/322952/54741456-d15e5300-4bbe-11e9-848d-2b01e8895178.png)

Let me know what you think.

Best,
Dmitry

**Comment by kervel** [comment]
Hi, 

thanks for the reply! i'll try with converters and come back if i have a usecase for subtyping. The example i gave can indeed be solved with converters, there might be cases that are suboptimal with converters but i'll come back when i stumble upon one.

closing this for now.

Frank

**Comment by Daguerreo** [comment]
> Hi,
> 
> thanks for the reply! i'll try with converters and come back if i have a usecase for subtyping. The example i gave can indeed be solved with converters, there might be cases that are suboptimal with converters but i'll come back when i stumble upon one.
> 
> closing this for now.
> 
> Frank

Just check the image channels in setInData and set to error state if you don't want to use converters (since using converter for images means splitting ImageData in multiple types with potentially a lot of implicit conversion)

**Comment by kervel** [comment]
Hi @Daguerreo , thanks for the hint (I saw "Azul" on your github account which might be related to what i'm trying to do, but i guess its a bit old)
