### ISSUE TITLE
Headless equivalent to execute flow

### ISSUE THREAD

**Issue by nyue** [paceholder/nodeeditor#222]
Hi,

  Is there a way to run an equivalent flow not as a UI application but a console application where there is no graphics driver/hardware at all ?

  I am looking for a headless equivalent.

Cheers

**Comment by klauer** [comment]
That's possible in the model-view-controller refactor of #117. It even includes a headless example: https://github.com/paceholder/nodeeditor/tree/1bb2562fb5e25f7fc680ec98294afa02092bc234/examples/headless

**Comment by jcelerier** [comment]
@nyue there are many available pure computation dataflow libraries - tbb::flow_graph (part of Intel TBB), https://github.com/cpp-taskflow/cpp-taskflow, https://github.com/RaftLib/RaftLib...

**Comment by Daguerreo** [comment]
> That's possible in the model-view-controller refactor of #117. It even includes a headless example: https://github.com/paceholder/nodeeditor/tree/1bb2562fb5e25f7fc680ec98294afa02092bc234/examples/headless

@klauer Can that branche be considered stable?

**Comment by MrAhmedSayedAli** [comment]
any update ?

**Comment by paceholder** [comment]
Implemented in v3
