### ISSUE TITLE
Node becomes selected only if moved or mouse released

### ISSUE THREAD

**Issue by DexterMagnific** [paceholder/nodeeditor#230]
Hi,

When clicking on a node on the view, it gets selected only when releasing the mouse button or start moving it.

Is it possible for the node to get selected as soon as there is a mouse press on it ?

Thanks

**Comment by paceholder** [comment]
Sorry, I do not see any benefit from doing that. Could you explain?

In your internet browser you don't follow the link immediately as you press your mouse button. The link is being opened as soon as you release the button. I followed this common workflow.

Dmitry

**Comment by DexterMagnific** [comment]
The drawback of your approach is that currently clicking a Node deselects the previous one, and you must wait until releasing the mouse before the new one gets selected.

So you get an intermediate state in which the previous one is selected and the new one no longer selected.

I have in my application a QWidget that shows the "properties" of a Node when it is selected, and I'm plugged on the selectionChanged() signal of the scene.

With the current behavior, I see my widget empty on click and filled of release. So every time I change Node there is a "flickering" because of the intermediate state where no Node are selected.

**Comment by paceholder** [comment]
Fixed in master.
