### ISSUE TITLE
Use pointers instead of refs

### ISSUE THREAD

**Issue by DexterMagnific** [paceholder/nodeeditor#231]
Hi,

I noticed in your code extensive use of return by reference instead of pointer return.
This is annoying for classes that have their copy constructor deleted.

My use case if the following: I'm iterating through the selected nodes to find the leftmost one in the scene.

```
NodeGraphicsObject &node = selectection[0]->nodeGraphicsObject();
foreach(auto n, selection) {
    if ( n.pos().x() < node.pos().x() )
       node = n; /* NOT POSSIBLE, QObject copy constructor is deleted */
}
```

Workaround: work with Node instead of NodeGraphicsObject, because selection[0] is Node *, not Node &.

And this is the case for many other scenarios where you return references instead of pointers. That's really hard to work like this.

What's the rationale behind returning references instead of pointers ? Even Qt does not do it.

Thanks

**Comment by jcelerier** [comment]
you should just do `NodeGraphicsObject *node = &selectection[0]->nodeGraphicsObject();` tand `node = &n;` then. references by default makes the semantics more precise than pointers where some people (and compilers) could ask "is this null ?".

**Comment by DexterMagnific** [comment]
Thank you, your code worked fine. I did not know that you can take a & of a returned by ref. Seems very logical now.

**Comment by Daguerreo** [comment]
You basically are opening a lot of issues because you don't know C++

**Comment by paceholder** [comment]
> You basically are opening a lot of issues because you don't know C++

Well, it is always better to ask and improve knowledge than to struggle with the problems alone.

**Comment by Daguerreo** [comment]
> > You basically are opening a lot of issues because you don't know C++
> 
> Well, it is always better to ask and improve knowledge than to struggle with the problems alone.

Of course, but maybe better asking than complaining with other :D
