### ISSUE TITLE
signal FlowScene::nodePlaced never emitted

### ISSUE THREAD

**Issue by DexterMagnific** [paceholder/nodeeditor#234]
Hi,

The nodePlaced() signal is never emitted. Only nodeCreated() on create and restore node.

**Comment by paceholder** [comment]
Do you mean just restoring process?

Because with the normal creation (mouse clicks) both signals are emitted.

**Comment by paceholder** [comment]
Fixed restoring signals

**Comment by DexterMagnific** [comment]
Do you also emit it when the programmer manually calls createNode() ?
