### ISSUE TITLE
dynamic_cast

### ISSUE THREAD

**Issue by sindney** [paceholder/nodeeditor#237]
https://github.com/paceholder/nodeeditor/blob/1151b597b3370977e656bd17e675543c22fc78fa/src/FlowScene.cpp#L650
Found 2 dynamic_cast here, i assume we should use qgraphicsitem_cast instead, so our app won't crash when there's not just NodeGraphicsObject in the scene.

**Comment by paceholder** [comment]
Sorry, I can't see how the app could crash here.
If the casted object `item` is not `NodeGraphicsObject`, then `dynamic_cast` would return nullptr and the whole lambda function returns `false`.
