### ISSUE TITLE
How is the branch node implemented?

### ISSUE THREAD

**Issue by ysx1993** [paceholder/nodeeditor#242]
![looping](https://user-images.githubusercontent.com/12573603/60000370-a6403f80-9696-11e9-8c12-eeb43463cc07.png)
How do the branch node choose different path based on different outputs?

I have found the traversal algorithm(**iterateOverNodeDataDependentOrder(std::function<void(NodeDataModel*)> visitor)**) in the source code but there seems to be no branch node related code...

I really want to understand the implementation, hope to get your help!

**Comment by Daguerreo** [comment]
This is a part of [Chigraph](https://github.com/chigraph/chigraph), you can find the implementation there

**Comment by paceholder** [comment]
Close as answered.
