### ISSUE TITLE
Cannot build, Linux

### ISSUE THREAD

**Issue by duncanam** [paceholder/nodeeditor#257]
I have all the dependencies, and make it to the step where I perform `make -j && make install`. I get hit with:

[error.log](https://github.com/paceholder/nodeeditor/files/4110030/error.log)

Any ideas?

**Comment by paceholder** [comment]
Hi Duncan,

it looks like the developers have added the implementation of std::hash<QString> in 5.13 and we do not need anymore the content of `include/nodes/internal/QStringStdHash.hpp`

See commit https://code.qt.io/cgit/qt/qtbase.git/commit/?id=4469e36d7203a55a4e158a50f0e9effc3f2fa3c2

I have Qt 5.13 on my machine as well and strangely can't reproduce your issue.

Temporarily you could comment out the content of `QStringStdHash.hpp` to proceed with your work.  I'll see what could be done.

Thanks

Dmitry

**Comment by paceholder** [comment]
Ok, it seems that the change made it to 5.14

**Comment by duncanam** [comment]
@paceholder Hi there, I believe that is now functioning on my end. It successfully installed when I comment out the content of that file. 

Additionally, I'm not sure if I'm going about compiling the examples the wrong way: 

1. navigate to example directory
2. `cmake CMakeLists.txt`
3. `make` then gives me an error:

``
[ 12%] Building CXX object CMakeFiles/calculator.dir/Converters.o
In file included from /usr/local/include/nodes/NodeDataModel:1,
                 from /home/duncan/github/external/nodeeditor/examples/calculator/DecimalData.hpp:3,
                 from /home/duncan/github/external/nodeeditor/examples/calculator/Converters.hpp:3,
                 from /home/duncan/github/external/nodeeditor/examples/calculator/Converters.cpp:1:
/usr/local/include/nodes/internal/NodeDataModel.hpp:4:10: fatal error: QtWidgets/QWidget: No such file or directory
    4 | #include <QtWidgets/QWidget>
      |          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/calculator.dir/build.make:76: CMakeFiles/calculator.dir/Converters.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/calculator.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
``

I'm probably missing something as I'm not incredibly familiar with this build process. Perhaps there's something I need to export or I am compiling them incorrectly?

**Comment by paceholder** [comment]
Typically I do this:

```
> cd nodeeditor
> mkdir build
> cd build
> cmake ..
> make -j
```

Afterwards all the examples are located in `nodeeditor/build/bin`

```
[paceholder@xps13 build]$ ls bin
calculator  connection_colors  example2  images  styles  test_nodes
```

**Comment by duncanam** [comment]
Ah, yes. They were already compiled. Everything looks good, I'll play around with it further and see what comes of it all! Thanks again. 

I don't know if you'd like me to close this issue now since I "solved" it by commenting out that file, but I am happy to.

**Comment by paceholder** [comment]
I've pushed the fix to the master, should be done now.

**Comment by duncanam** [comment]
I removed, recloned, and followed the README and it all functioned as expected. Thanks again!
