### ISSUE TITLE
Headless Mode

### ISSUE THREAD

**Issue by hardliner66** [paceholder/nodeeditor#26]
I experimented a bit with your library and it seems that I can only run in interactive mode (Showing the editor). It would be cool if I could design a flow in the editor, save it to a file and run the saved file without  the need for the editor itself.

For example: The unreal engine uses a similar editor system called "Blueprints" where you can visually design program flow. But after shipping, the editor itself is not needed anymore and the generated files can be interpreted by it's own.

**Comment by paceholder** [comment]
I see your point and I agree with the proposed workflow. I just can say, that I was focusing on the graphics and tried to make a general-purpose node editing tool. 

The computational process is the next step and there one could invent many fancy features (off-screen run, [parallelization](http://www.raftlib.io/), high-frequency data exchange, [llvm-bytecode compilation](https://github.com/russelltg/chigraph) etc).

Anyway, I will think about possible implementation.

**Comment by russelltg** [comment]
Seems like a good fit for the MVC pattern :).

Also, I have implemented a similar thing using the hooks in `FlowScene` and in `Connection` that uses my own data structure that can be serialized.  This is actually for a language quite similar to UE4 blueprints (it's designed around it but to be general and faster) Check out [a link](https://github.com/russelltg/chigraph) .

I can help with the LLVM bytecode stage, I use it to compile chigraph.

**Comment by MrAhmedSayedAli** [comment]
@paceholder  any update ??
