### ISSUE TITLE
OpenGL/3D display node ?

### ISSUE THREAD

**Issue by nyue** [paceholder/nodeeditor#261]
Hi,

  I am looking at the images example as a starting point.

  Has anyone written an equivalent image node but for OpenGL/3D ? Any advice ?

  I am thinking of prototyping something that read in e.g. a Wavefront file in one node and pass the data to a 3D node to display

  If I also need to provide Pan-Zoom-Rotate in the 3D node, is there anything else to take note of ?

Cheers

**Comment by theHamsta** [comment]
I used a OpenGL image widget if mine and in worked perfectly. The only issue was to handle mouse/key board input and split in properly between the nodes and the widget itself. just embed a a OpenGLWidget

**Comment by paceholder** [comment]
I hope the question has been answered. I personally did not try to embed something with OpenGL into a node.
