### ISSUE TITLE
Deleting multiple nodes and connections crashes

### ISSUE THREAD

**Issue by spiriapbergeron** [paceholder/nodeeditor#262]
FlowView::deleteSelectedNodes() crashes when multiple nodes and multiple connections are currently selected.

eg: In the calculator example, do a big graph with many adds, then try to delete the middle portion of the graph. boom.

The issue is that "_scene->selectedItems()" will return multiple elements, among them nodes and connections... If we first delete the nodes (eg: _scene->removeNode()) then the call to removeNode will also remove attached connections.

Then when we do a next iteration, the call to qgraphiucsitem_cast<> will crash because the item (a connection) will have already been deleted.

The fix is simple: delete all connections first, then delete the nodes (eg: change the order of the loops).

The correct implementation should be this: 

void
FlowView::
deleteSelectedNodes()
{
    // Delete connections first because _scene->removeNode() will delete connections that are in the selectedItems() list
    for (QGraphicsItem * item : _scene->selectedItems())
    {
        if (auto c = qgraphicsitem_cast<ConnectionGraphicsObject*>(item))
        {
            _scene->deleteConnection(c->connection());
        }
    }

    // Now delete the disconnected nodes and clean up any remaining connections attached to those nodes.
    for (QGraphicsItem * item : _scene->selectedItems())
    {
        if (auto n = qgraphicsitem_cast<NodeGraphicsObject*>(item))
        {
            _scene->removeNode(n->node());
        }
    }
}

**Comment by Daguerreo** [comment]
@spiriapbergeron I cannot replicate the issue, could you add a scene like you described?

**Comment by spiriapbergeron** [comment]
Ugh. It's been quite a while. I have a heavily modified version here locally, so it's not easy to "send a scene" since I have also changed the persistence scheme on my end.

But, let me try to be clearer in my explanation: 
- Using the calculator example, create a "big graph", where you add together about 12 nodes.

A \                       E\
B ---- (A+B)   ------- E+(A+B)     \
C ---- (C+D)  ------- F+(C+D)     ------ (E+(A+B)) + (F+(C+D)) -----> result node.
D /                      F /

Do a rectangle selection over the following nodes, AND their connections.

The add node for (A+B)
The add node for (C+D)
The data node E
The data node F
The add node for E+(A+B)
The data node for F+(C+D)
The add node for the result.

Then hit delete.

Or, in other words, only leave as unselected the following nodes (but select all connections)
Data node A,B,C,D, Result.
Hit Delete.

You should crash.

**Comment by Daguerreo** [comment]
I just tried and it works properly again

**Comment by spiriapbergeron** [comment]
You mean you can reproduce and you fixed it, or you can't reproduce?

**Comment by Daguerreo** [comment]
Sorry, I mean I can't reproduce it. Are you sure it not depends from your locally modified version?
