### ISSUE TITLE
std::hash<QString> has been defined by Qt in latest versions

### ISSUE THREAD

**Issue by ShuangLiu1992** [paceholder/nodeeditor#264]
nodes/internal/QStringStdHash.hpp:11:8: error: redefinition of ‘struct std::hash<QString>’
 struct hash<QString>

Qt/gcc_64/include/QtCore/qhashfunctions.h:204:1: note: previous definition of ‘struct std::hash<QString>’

**Comment by Daguerreo** [comment]
This has been already fixed in #257
