### ISSUE TITLE
Automatic layout / vertical layout

### ISSUE THREAD

**Issue by Squelsh** [paceholder/nodeeditor#266]
First of all: Amazing project!! Just love it.

Now to my questions as I could not find anything about it:

1) Are there any plans to add some kind of automatic layout / arrangements of nodes? By defining virtual forces between nodes or even by an external library like GraphViz?

2) Any thoughts about making the layout switchable to a vertical layout where the connections go from top to bottom?

Cheers,
Andy

**Comment by paceholder** [comment]
The vertical layout is here https://qtnodes.readthedocs.io/en/latest/features.html#vertical-layout
Automatic layout would need some further work. Thanks for the idea.
