### ISSUE TITLE
Dynamic adding ports

### ISSUE THREAD

**Issue by DmitruMoth** [paceholder/nodeeditor#272]
Is it possible to add new ports (out and in) dynamic? For example, i pressed the button in node, and it add new out pin in this node

**Comment by paceholder** [comment]
It's not fully implemented but you could try this PR https://github.com/paceholder/nodeeditor/pull/268

**Comment by paceholder** [comment]
This question duplicates #209

**Comment by Daguerreo** [comment]
> Is it possible to add new ports (out and in) dynamic? For example, i pressed the button in node, and it add new out pin in this node

I made one which support port shifting and dynamic loading/save [here ](https://github.com/Daguerreo/NodeEditor/tree/dynamic-ports)

![2020-12-20-17-39-01](https://user-images.githubusercontent.com/6747152/102718981-81f50b80-42eb-11eb-96b5-d8f9010df8d9.gif)

description of the feature [here](https://github.com/Daguerreo/NodeEditor/issues/7)

**Comment by paceholder** [comment]
Addressed in the v3
