### ISSUE TITLE
Mac OS X embedded widget (and its children) rendering issue.

### ISSUE THREAD

**Issue by skarnproject** [paceholder/nodeeditor#278]
This is more of a warning of an existing QT bug, rather than an issue in the node editor library itself. Due to this bug which is still unfixed https://bugreports.qt.io/browse/QTBUG-48681, the widgets will appear borked when the view is zoomed in. Can be tested on the calculator example.

Workaround: Since it is a QT bug and only happens on Mac OS X with **Macintosh application style on**, the only solution that I was able to find is to change application's style to something else than Macintosh. I personally use Fusion, and the issue vanished. Windows works as well.

**Comment by paceholder** [comment]
Thanks for the notice. I'll close this issue having in mind your warning.
