### ISSUE TITLE
cmake Error when I cloned and tried building

### ISSUE THREAD

**Issue by srihari-vistrian** [paceholder/nodeeditor#280]
Make Error at /Users/srihari/Qt/5.15.2/clang_64/lib/cmake/Qt5Core/Qt5CoreMacros.cmake:80 (file):
  file attempted to create a directory:
  /Users/srihari/Software/nodeeditor/resources into a source directory.
Call Stack (most recent call first):
  /Users/srihari/Qt/5.15.2/clang_64/lib/cmake/Qt5Core/Qt5CoreMacros.cmake:256 (qt5_make_output_file)
  /Users/srihari/Qt/5.15.2/clang_64/lib/cmake/Qt5Core/Qt5CoreMacros.cmake:339 (_qt5_parse_qrc_file)
  CMakeLists.txt:48 (qt5_add_resources)

-- Configuring incomplete, errors occurred!
See also "/Users/srihari/Software/nodeeditor/CMakeFiles/CMakeOutput.log".
See also "/Users/srihari/Software/nodeeditor/CMakeFiles/CMakeError.log".

**Comment by srihari-vistrian** [comment]
I'm a NOOB here and not sure if there is something I'm missing in the steps as I followed the doc. If this is not really an issue, some suggestions as to what might be wrong with my setup would be very much appreciated.

Sorry if this is a false alarm!

> Make Error at /Users/srihari/Qt/5.15.2/clang_64/lib/cmake/Qt5Core/Qt5CoreMacros.cmake:80 (file):
> file attempted to create a directory:
> /Users/srihari/Software/nodeeditor/resources into a source directory.
> Call Stack (most recent call first):
> /Users/srihari/Qt/5.15.2/clang_64/lib/cmake/Qt5Core/Qt5CoreMacros.cmake:256 (qt5_make_output_file)
> /Users/srihari/Qt/5.15.2/clang_64/lib/cmake/Qt5Core/Qt5CoreMacros.cmake:339 (_qt5_parse_qrc_file)
> CMakeLists.txt:48 (qt5_add_resources)
> 
> -- Configuring incomplete, errors occurred!
> See also "/Users/srihari/Software/nodeeditor/CMakeFiles/CMakeOutput.log".
> See also "/Users/srihari/Software/nodeeditor/CMakeFiles/CMakeError.log".

**Comment by srihari-vistrian** [comment]
I cleaned up all the cmake cache files and tried again outside of QT creator and it worked fine this time. Must have been some local setup issue on my sys.

**Comment by mohamad76wp** [comment]
> I cleaned up all the cmake cache files and tried again outside of QT creator and it worked fine this time. Must have been some local setup issue on my sys.

can you explain what did you do ?

**Comment by srihari-cd** [comment]
I removed the build files created when I opened and tried to build using QTCreator.
`rm -rf build `
`rm  CMakeLists.txt.user`
