### ISSUE TITLE
"The program has unexpectedly finished."

### ISSUE THREAD

**Issue by cesarcherre848** [paceholder/nodeeditor#283]
Install the library using cmake, import my files to .pro but when running the program it appears 
"The program has unexpectedly finished."

Pd. Copy .dll and .a to the folder where the build debug will be done.

Could you help me with this?

**Comment by Daguerreo** [comment]
Without any information how we can possibly help? Have you at least tried to run it in debug mode? The samples run correctly?

**Comment by paceholder** [comment]
What do you mean with "import my files to .pro" ?

**Comment by cesarcherre848** [comment]
This is a image of debug console :

![image](https://user-images.githubusercontent.com/77457841/104744887-6c70d700-571b-11eb-8d34-26a4678db5bc.png)

**Comment by paceholder** [comment]
Looks like you did not link the nodes library to your executable

**Comment by cesarcherre848** [comment]
Yes, you are right,  just guide from @Daguerreo , thanks so much, node editor works perfectly now. Congrats for your qt project
