### ISSUE TITLE
Add support for Qt6 (minor depcrecated replacements)

### ISSUE THREAD

**Issue by Broekman** [paceholder/nodeeditor#288]
Below a minor list of changes I had to make. If agreed I can make a PR later.

```
In:
QColor ConnectionStyle::normalColor(QString typeId) const

Replace qsrand with std::srand and qrand with std::rand
  std::srand(hash);
  std::size_t hue = std::rand() % hue_range;
```

```
In
unsigned int NodeGeometry::portWidth(PortType portType) const

_fontMetrics.width(...) to _fontMetrics.boundingRect(name).width()
```

So far no problems with Qt6.

**Comment by Daguerreo** [comment]
Both fixed here https://github.com/Daguerreo/NodeEditor and added cmake support for Qt6

**Comment by Broekman** [comment]
Hi @Daguerreo, thanks but I still would like to see it back inside the main repo in the end, instead of a fork. We could use your repo for the PR, however looks like Paceholder isn't very active at the moment.
