### ISSUE TITLE
Could you provide guidelines on using this?

### ISSUE THREAD

**Issue by s1nisteR** [paceholder/nodeeditor#290]
It'd be great if there was some guideline available on how to integrate this node editor into existing CMake projects.

**Comment by paceholder** [comment]
Hi,

the guidelines are those from the CMake documentation.

1. add this project as a sub-probject to your source tree.
2. write in your root `CMakeListst.txt` : `add_subdirectory(nodeeditor)`.
3. Link to the target `NodeEditor::nodes`
