### ISSUE TITLE
V3 Changing node position not reported to AbstractGraphModel

### ISSUE THREAD

**Issue by marack** [paceholder/nodeeditor#297]
I realize that the v3 branch is still in alpha - but wanted to report this in case it hasn't been noticed yet.

When dragging a node around with the mouse the underlying graph model (extending `AbstractGraphModel`) is not receiving any calls to `setNodeData()` with `role == NodeRole::Size`.  This means that the model has no ability to monitor movements caused by the user dragging nodes around the scene.

The main impact is that when serializing a graph model, the position reported via `nodeData()` is incorrect and most likely the original position the node was inserted to.  When the graph is later loaded from disk nodes are positioned back to their original creation locations instead of the locations they had when saved.

**Comment by paceholder** [comment]
Thanks a lot for noticing that! Fixing it now.
