### ISSUE TITLE
Maybe made examples to releases tab?

### ISSUE THREAD

**Issue by lurumdare** [paceholder/nodeeditor#3]
##

**Comment by paceholder** [comment]
You mean examples of the code made with the library?  Is the ```example``` directory in the codebase not enough? Or I do not get your point?

Sorry, I've never used the releases tab for any purposes

**Comment by brainblowjob** [comment]
Compiled example program.

**Comment by paceholder** [comment]
Binaries are not added automatically to the github page yet but they are available here

https://ci.appveyor.com/project/paceholder/nodeeditor/branch/master

![image](https://user-images.githubusercontent.com/322952/27828961-44017dc0-60bf-11e7-9c3e-7a8fcebfc5b6.png)
