### ISSUE TITLE
Look at reviewable.io for pull requests

### ISSUE THREAD

**Issue by russelltg** [paceholder/nodeeditor#30]
The github PR interface is a bit lacking (in my opinion).

I have used [reviewable.io](https://reviewable.io) on other projects and it is quite nice.

(You don't even have to enable it, you can preview it by looking at my new PRs on it)

https://reviewable.io/reviews/paceholder/nodeeditor/28#-
https://reviewable.io/reviews/paceholder/nodeeditor/29#-

**Comment by paceholder** [comment]
Slow UI, no real benefits. But thanks for suggesting.
