### ISSUE TITLE
Destructing a Connection propagates empty data even without an output node

### ISSUE THREAD

**Issue by vhutter** [paceholder/nodeeditor#307]
Not sure if the behavior is intended, but it seems to me that it's unnecessary. I assumed that propagating empty data is only useful if there was a non-empty propagation for the respective connection directly prior to the empty one.

Steps to reproduce:
1. Click to an input node of a data node.
2. Move the mouse anywhere, but don't connect the other end to an output node.
3. Release the mouse.

This will result in the connection's destructor firing a signal, that will be handled by the respective node's data model type.

My suggestion is changing Connection::~Connection from

```cpp

Connection::
~Connection()
{
  if (complete())
  {
    connectionMadeIncomplete(*this);
  }

  propagateEmptyData();

  if (_inNode)
  {
    _inNode->nodeGraphicsObject().update();
  }

  if (_outNode)
  {
    _outNode->nodeGraphicsObject().update();
  }
}

```

to 
```cpp

Connection::
~Connection()
{
  if (complete())
  {
    connectionMadeIncomplete(*this);
  }

  if (_inNode)
  {
    _inNode->nodeGraphicsObject().update();
  }

  if (_outNode)
  {
    propagateEmptyData();
    _outNode->nodeGraphicsObject().update();
  }
}
```

@paceholder If you approve, I can make a quick PR.

**Comment by paceholder** [comment]
Hi, thanks for your suggestion.

Don't we already have the desired behavior? Let's look at the function calls chain:

`propagateEmptyData();`
`propagateData("empty");`

and now

```
void
Connection::
propagateData(std::shared_ptr<NodeData> nodeData) const
{
  if (_inNode)     <<< Here we check that we actually had a node on the right hand side.
  {

   ....

    _inNode->propagateData(nodeData, _inPortIndex);
  }
}
```

Am I missing something?

**Comment by vhutter** [comment]
Hi,

I think you misunderstood the issue. I also made a typo in my description. In "Step 1", I meant "input _port_ of a data node", so as you correctly displayed it on your diagram, the **in port**  of the node on the **right**. Step 2 is actually unimportant. The main point is to create a half-connection, only with the input port attached to it, and releasing the mouse before connecting it to an output port (left side).

To give another demonstrative example, if you simply click on an input node 10 times (not even moving the mouse), the respective Node's corresponding NodeDataType::setInData will be triggered 10 times by Connection::propagateData (with nullptr as an argument).
This is what I found unnecessary, since it would be nice if this method was only called when an __actual__ data change happens, so in either of these 3 cases:
- valid data -> another valid data
- valid data -> nullptr
- nullptr -> valid data

and **NOT** in case nullptr -> nullptr, which is currently happening. I think that's redundant to handle in client code.

**Comment by paceholder** [comment]
I see your point now, thanks for the explanation. Let's fix it.

**Comment by vhutter** [comment]
I opened a PR for it: https://github.com/paceholder/nodeeditor/pull/308

**Comment by paceholder** [comment]
Thanks
