### ISSUE TITLE
When a node connects multiple child nodes, all child nodes will execute repeatedly

### ISSUE THREAD

**Issue by LiuPeiqiHN** [paceholder/nodeeditor#312]
Suppose I have a node A, and A have a out port connected to child nodes B1,B2,B3,B4.

If I disconnect and reconnect A and B1 (or add a child node and connect to A), node A will triggered the `onDataUpdated()` event, then all child nodes who connect to A will all be executed, even I just reconnect A and B1, but B2,B3,B4 will all be executed too.

If I restore from .flow file, B1 will execute one time, B2 will execute two times, B3 will execute 3 times, B4 will execute 4 times! Normally, B1~B4 will all execute just one time!

**Comment by paceholder** [comment]
That's a good observation, I'll check and address it. Thanks

**Comment by paceholder** [comment]
Fixed in master.
