### ISSUE TITLE
Unable to disable connection drugging from node 

### ISSUE THREAD

**Issue by RazmikKarapetyan** [paceholder/nodeeditor#317]
We are using nodeeditor for graph visualisation, but we need to disable editing  of connections after creating them initially.
**Lock(true)** method of **ConnectionGraphicsObject** method does not provide that functionality, and disabling mouse events on **ConnectionGraphicsObject** is fixing the connection drugging issue, but we are having some rendering issues on the connection object.

Could you please let us know is it possible to achieve non  modifiable connections via your native implementation?

Thanks in advance.

**Comment by paceholder** [comment]
Hi,

I decided to implement it in a new version rather than fixing v2.
https://qtnodes.readthedocs.io/en/latest/features.html#locked-nodes-and-connections

Contact me if you need further help
