### ISSUE TITLE
[v3alpha] An issue with the working of draft connection

### ISSUE THREAD

**Issue by velorom** [paceholder/nodeeditor#318]
In `ConnectionGraphicsObject` on `mouseMove` event you transfer self to hovered node for reaction:
`ngo->reactToConnection(this);`
This connection is using in `NodePainter::drawConnectionPoints` for painting ports. And you reset this pointer at the end of this method.
But sometimes `mouseRelease` event of `ConnectionGraphicsObject` and corresponding destroying of draft connection happens before `NodePainter::drawConnectionPoints` call. 
So sometimes `NodePainter` accesses the destroyed pointer.

I think you need to let the scene set reaction connection to nodes and tracks for it destruction.

**Comment by paceholder** [comment]
Thanks for pointing this out, I'll have a look in the nearest days.

**Comment by paceholder** [comment]
1. I used QPointer<ConnectionGraphicsObject>, it is cleared automatically when the object inside is destroyed.
2. To me the two options were not clearly distinguishable. [ItemPositionChange](https://doc.qt.io/qt-6/qgraphicsitem.html#GraphicsItemChange-enum), [ItemPositionHasChanged](https://doc.qt.io/qt-6/qgraphicsitem.html#GraphicsItemChange-enum). Now I see the difference. 

Thanks for your valuable and inspective remarks!
