### ISSUE TITLE
Library for commonly used NodeDataModel implementation

### ISSUE THREAD

**Issue by Yadunund** [paceholder/nodeeditor#320]
Hi @paceholder ,

This is a really cool project!

I'm wondering if there is a repo somewhere or document that collates all the user implemented `NodeDataModels` so that they can be reused by the community?

The `examples/` folder is great but models are not shared between the examples there. It would be awesome if there is a separate library that exports a common set of nodes.

**Comment by paceholder** [comment]
Hi @Yadunund ,

I am afraid that the library is general enough that it would be hard to collect some "common" model implementations.
In most cases the consumers of the library modify it to answer their specific needs.

Let met know if you have some more specific requests.

Best,

Dmitry

**Comment by Yadunund** [comment]
Gotcha, thanks for the quick response!
