### ISSUE TITLE
Impossible to pull connection from a connected in port

### ISSUE THREAD

**Issue by AokiYuune** [paceholder/nodeeditor#327]
Hello, paceholder! Thanks for your great library.
In most node editor, when user pull connection from a connected in port, they disconnect the previous one and connect the new one. May support it?

**Comment by paceholder** [comment]
Hi @AokiYuune ,

I think the desired behavior depends on the port's policy. For "many"  a mouse-pull from the port initiates a new connection. For "one" it detaches the connection.

**Comment by AokiYuune** [comment]
I see. Thanks for your reply.

**Comment by AokiYuune** [comment]
https://user-images.githubusercontent.com/43339352/203033306-fb0de051-3be6-4ac4-9cf6-1c37a96da5b6.mp4

Hi @paceholder ,
I tried to change NodeDataModel::ConnectionPolicy, but still cannot get the expected result. Pls see the video, I want to pull new connection to replace the old one. I can work for a PR to match this desire, if you wish to.
