### ISSUE TITLE
find_package() macro creates incompatibilities and should not be used

### ISSUE THREAD

**Issue by Ivansstyle** [paceholder/nodeeditor#328]
from: [nodeeditor](https://github.com/paceholder/nodeeditor)/[external](https://github.com/paceholder/nodeeditor/tree/master/external)/CMakeLists.txt
```
macro(find_package pkg)
  if(NOT TARGET "${pkg}")
    _find_package(${ARGV})
  endif()
endmacro()
```
Using redefinition of find_package() causes errors and incompatibilities with many libraries (OpenEXR, anything installed with vcpkg). Plese consider redefining to a different macro and updating dependant CMakeLists.
Example:  
```
macro(_nodeeditor_find_package pkg)
  if(NOT TARGET "${pkg}")
    _find_package(${ARGV})
  endif()
endmacro()
```

**Comment by paceholder** [comment]
Please, see the pull request https://github.com/paceholder/nodeeditor/pull/329
Could you check if it works now?

**Comment by paceholder** [comment]
I hope it was fixed in master. Let me know if something does not work.
