### ISSUE TITLE
will this great project support Group Nodes?

### ISSUE THREAD

**Issue by isteelcx** [paceholder/nodeeditor#336]
when will your great project support Group Nodes?

**Comment by isteelcx** [comment]
> I cannot provide you an exact timeline, I'am working on the code in my free time. This is the next featue I want to work on

**Comment by isteelcx** [comment]
> I cannot provide you an exact timeline, I'am working on the code in my free time. This is the next featue I want to work on

Creating a great Qt library that is popular is really hard and fun work, and the GUI itself is an artistic visual sensation.

1.I believe that such a connect line is more beautiful and should be kept as an optional style
![image](https://user-images.githubusercontent.com/45957575/204319795-ee0e5c1e-ca7a-4666-8fb1-f8d9a696f303.jpeg)
2. Shape-changing nodes are also a good extension to support a common application scenario.
![image](https://user-images.githubusercontent.com/45957575/204322880-f9d9a3f9-5b6f-4eb8-9db8-f7c009039a2b.jpeg)

**Comment by isteelcx** [comment]
@paceholder Maybe my question got you thinking...

**Comment by paceholder** [comment]
As I said, group nodes are planned for implementation.
Custom node and connection shapes will be available when I finish classes for fully custom drawing

**Comment by isteelcx** [comment]
Will you change the basic architecture of QSchematic in the future?

**Comment by paceholder** [comment]
Sorry, I did not get your question. QSchematic is not my project, what am I suppose to change there?

**Comment by isteelcx** [comment]
> Will you change the basic architecture of QSchematic in the future?

Sorry for this... I mean your project！

**Comment by paceholder** [comment]
ok, what do you mean under "basic architecture" and what should or shouldn't be changed?

**Comment by isteelcx** [comment]
Basic architecture refers to the basic implementation mechanism and design pattern of the project, such as model-view design pattern and basic abstract class. This problem mainly concerns whether the users of your project will be unable to continue to use the new features of your project in the long-term function development because you change the basic framework. The reason you change the underlying framework may be that one day you come up with a better and more rational way to implement the framework

**Comment by isteelcx** [comment]
In addition, I found an open source project that is very close to the final form of your project--https://github.com/jchanvfx/NodeGraphQt

**Comment by paceholder** [comment]
You are free to choose whatever project better suits your needs. There are dozens of node editor implementations.
Thanks for the link though, I starred this project but did not look into it for a long time. Maybe I can steal some good features.

I am not planning to change the model-view approach, I think it addresses most of the requests to the library design.

**Comment by isteelcx** [comment]
Your project has so many followers, but there seem to be so few actual committers. Is that the main reason why you don't update for so long?
