### ISSUE TITLE
Some nodes don't show captions when they are long

### ISSUE THREAD

**Issue by russelltg** [paceholder/nodeeditor#35]
I've noticed that some nodes don't show captions or even port labels if they are too long. 

For example, if you change `SubtractionModel::caption` in `SubtractionModel.hpp` to:
```C++
return QString("Subtraction1233456789012345678901234567890");
```
It appears like this:

![spectacle ns8848](https://cloud.githubusercontent.com/assets/7105082/21412698/7c49d460-c7af-11e6-951b-5018033f8e01.png)

I haven't really looked at the rendering code yet, so I don't know where to look to form a PR. 

Interestingly enough, it is dependent on the `embeddedWidget`. All of the below nodes have the caption `somelongstring`:

![spectacle wz8848](https://cloud.githubusercontent.com/assets/7105082/21412788/1024a6b0-c7b0-11e6-8044-ef20cc82b48e.png)

yet only the one with the embedded widget has the caption...

I think the trust should be put in the developer for not creating a name that is too long (I have had this issue with significantly shorter names and it makes things quite unreadable)

**Comment by paceholder** [comment]
I will fix it, thanks for reporting

**Comment by paceholder** [comment]
btw, such a fancy GUI ;)

**Comment by paceholder** [comment]
resolved in 
https://github.com/paceholder/nodeeditor/commit/f2875edfbe988c8bcd8111c2bb68b10899a61f48

**Comment by russelltg** [comment]
You're a life saver, works much better now :)
