### ISSUE TITLE
bug: `QJsonValueConstRef` in UndoCommands.cpp 

### ISSUE THREAD

**Issue by QianMoth** [paceholder/nodeeditor#353]
UndoCommands.cpp
insertSerializedItems
77 and 90
```cpp
77 for (QJsonValueConstRef node : nodesJsonArray)
...
90 for (QJsonValueConstRef connection : connJsonArray)
...
```
in this commit
https://github.com/paceholder/nodeeditor/commit/4767ddb416f7a192991d53d63cbadb17ceb5716e

Hi @paceholder , Compilation does not pass, please fix as soon as possible.

I did not find a description of the class `QJsonValueConstRef` in the qt documentation.

**Comment by paceholder** [comment]
Sorry for that. It must be something from Qt6 which I have on my computer. Will fix immediately

**Comment by paceholder** [comment]
The type name is mentioned here but is not documented properly yet

https://doc-snapshots.qt.io/qt6-dev/qjsonobject-const-iterator.html#value

**Comment by QianMoth** [comment]
> Sorry for that. It must be something from Qt6 which I have on my computer. Will fix immediately

```bash
\error C2065: “QJsonValueConstRef”: Undeclared identifiers
```
my qt version is 6.2.1

**Comment by QianMoth** [comment]
Why is `QJsonValueRef` displayed when I use `auto` auto-completion, is this different from `QJsonValue`?

**Comment by paceholder** [comment]
I think `QJsonValueRef` wraps both types QJsonValue and QJsonObject. You can write into object without explicit casting. I personally find all this classes a bit confusing. But the bug must be solved now

**Comment by paceholder** [comment]
```
[QJsonValueRef](https://doc.qt.io/qt-5/qjsonvalue.html#qjsonvalueref) is a helper class for [QJsonArray](https://doc.qt.io/qt-5/qjsonarray.html) and [QJsonObject](https://doc.qt.io/qt-5/qjsonobject.html). When you get an object of type [QJsonValueRef](https://doc.qt.io/qt-5/qjsonvalue.html#qjsonvalueref), you can use it as if it were a reference to a QJsonValue. If you assign to it, the assignment will apply to the element in the [QJsonArray](https://doc.qt.io/qt-5/qjsonarray.html) or [QJsonObject](https://doc.qt.io/qt-5/qjsonobject.html) from which you got the reference.
```

**Comment by QianMoth** [comment]
Thank you for your explanation
