### ISSUE TITLE
BasicGraphicsScene::nodeMoved is not being emitted anywhere

### ISSUE THREAD

**Issue by rayment** [paceholder/nodeeditor#364]
I require the use of `BasicGraphicsScene::nodeMoved` (via. `DataFlowGraphicsScene`) for my project as I wish to determine when nodes have been moved. When I checked the code, the signal is not being emitted anywhere at all.

Under the assumption that this signal _should_ be implemented and not left to the user, I have thought of two simple solutions, though each are diametric to one another:

- Emit the signal directly in `BasicGraphicssScene::onNodePositionUpdated`. This produces a signal on every draw frame that the node is being dragged on. It's also redundant because `nodePositionUpdated` is already a signal.
- Emit the signal from a new slot called `BasicGraphicsScene::onNodeClicked`. This can produce a signal once, when the node has been dragged after at least one frame, and the mouse has been released.

I liked the second solution better, and have implemented it in my fork [here](https://github.com/rayment/nodeeditor/commit/a02f2268d5d1cdb84a682738d47359b7722adebe). Alternatively, my implementation for the first solution is as follows:

```c++
void BasicGraphicsScene::onNodePositionUpdated(NodeId const nodeId)
{
    auto node = nodeGraphicsObject(nodeId);
    if (node) {
        auto pos = _graphModel.nodeData(nodeId, NodeRole::Position).value<QPointF>();
        node->setPos(pos);
        node->update();
        Q_EMIT nodeMoved(nodeId, pos);
    }
}
```

Please let me know if this change is useful, and if so, I'll open a PR.

**Comment by rayment** [comment]
Looks like this issue is much bigger than this. After the version upgrade to `3.x.x`, a lot of these slots are no longer called including `inputConnectionCreated/Deleted` and `outputConnectionCreated/outputConnectionDeleted` after `src/FlowScene.cpp` was removed (see [PR 211](https://github.com/paceholder/nodeeditor/pull/211) when it was introduced).

**Comment by paceholder** [comment]
Thanks for addressing it. Indeed, some slots might have gone lost during refactoring (unintentionally). 
I'll have a look at your PR
