### ISSUE TITLE
Hi author!

### ISSUE THREAD

**Issue by kundezui** [paceholder/nodeeditor#382]
@paceholder 
Thank you very much for reading this letter in your busy schedule. Here are the problems I'm having with QtNodes:

I have successfully installed the latest version of QtNodes and I know that the sample projects are in the "nodeeditor/build/bin/" path. My environment is Ubuntu 18.04 and Qt5.14.2. When I run ". /resizable_images", the following window pops up when I use the right mouse button, and nothing happens when I click on either ImageLoaderModel or ImageShowModeld with the left mouse button. I have also run other projects inside the examples folder, such as calculatord, etc., and again there is no response. I don't know if my environment is wrong or if there is something wrong with my operation?
![image](https://user-images.githubusercontent.com/77045200/229041623-917697a9-61b8-4bae-899c-ab983dfe2e7f.png)
![image](https://user-images.githubusercontent.com/77045200/229041710-17c97d70-778b-4a26-b24f-6c857c69bf45.png)

I look forward to hearing from you.

**Comment by zmoth** [comment]
请检查以下各版本。不建议低于以下版本。
Linux (x64, gcc-7.0, clang-7)
Qt >5.15
CMake 3.8
Catch2

**Comment by kundezui** [comment]
> @zmoth 
Do you think this advice will solve my problem? In your previous suggestion #374issues
[https://github.com/paceholder/nodeeditor/pull/374](url)
![image](https://user-images.githubusercontent.com/77045200/229259219-96392284-8da2-4d54-9e82-471c6291d429.png)

**Comment by zmoth** [comment]
这个review是给我看的，并不影响运行。

**Comment by kundezui** [comment]
> 这个review是给我看的，并不影响运行。

@zmoth 
Do you mean that under normal circumstances, running any sample project under the "./build/bin" path will not cause incomplete functions? If there is incomplete function, it may be caused by the problem of related dependency version?

**Comment by paceholder** [comment]
Unfortunately it is hard to say what might have gone wrong with your code. Didn't you try to look into debugger?
I doubt that something was wrong with the models. Maybe a signal from Qt was changed between versions and I did not process it correctly.
