### ISSUE TITLE
Hi author!

### ISSUE THREAD

**Issue by kundezui** [paceholder/nodeeditor#385]
Thank you very much for reading this letter in your busy schedule. Here are the problems I'm having with QtNodes:

In the QtNodes3.0 version, I found that when using a connecting line to link two nodes, the output of the previous node will be transmitted to the input of the next node immediately. Run "./examples/text" as shown below. I want to set a "run" button, even when the connection line is connected, no data transmission will be performed between the nodes. Is it possible to modify the source code of QtNodes3.0? If possible, please tell me where to modify it.
![J_0C5LYWQXD3@QLFXO}}GB2](https://user-images.githubusercontent.com/77045200/232355984-555c8494-fc41-4a42-8aea-d77133efcc25.png)

**Comment by QiuYilin** [comment]
S the outDataUpdated() signal and comment out the relevant code.
