### ISSUE TITLE
How to create node control-flow-based ?

### ISSUE THREAD

**Issue by ChivenZhang** [paceholder/nodeeditor#387]
I want to use this solution, but I am confused about whether this framework can create control-flow based node. The pictures below show two different types: **data-flow** based / **control-flow** based.

![200W@F8ZT`COH}X9LGB~T1H](https://user-images.githubusercontent.com/48938612/235281444-df76e5e2-b96d-4934-991c-9fc8971d0a43.png)

![F4OT5AT(}$Q3OVEU30REEQK](https://user-images.githubusercontent.com/48938612/235281453-6710291a-bcd2-40c0-981f-6e6f27e68f66.png)

**Comment by kundezui** [comment]
Hello. Do you know if the shape and position of the node ports in QtNodes can be changed? For example, change the circular port to a rectangular port, move the circular port embedded in the edge of the node to the outside of the node, etc. If it can be changed, which function in the file needs to be rewritten?

**Comment by paceholder** [comment]
@ChivenZhang  could you please describe how exactly this "control flow port" works? Does it launch the recalculation upon arriving a signal? And the other ports do not to such an operation?

**Comment by QiuYilin** [comment]
In my option,you can easily use NodeEditor to modify the interactive GUI of various flow graphs, but you need to create additional underlying logic to implement control flow, including the execution order of all nodes.  The existing DataflowModel just realizes the function of data dissemination between nodes

> I want to use this solution, but I am confused about whether this framework can create control-flow based node. The pictures below show two different types: **data-flow** based / **control-flow** based.
> 
> ![200W@F8ZT`COH}X9LGB~T1H](https://user-images.githubusercontent.com/48938612/235281444-df76e5e2-b96d-4934-991c-9fc8971d0a43.png)
> 
> ![F4OT5AT(}$Q3OVEU30REEQK](https://user-images.githubusercontent.com/48938612/235281453-6710291a-bcd2-40c0-981f-6e6f27e68f66.png)

**Comment by ChivenZhang** [comment]
got it. Thanks
