### ISSUE TITLE
Widget with label: size issue after text update

### ISSUE THREAD

**Issue by yvanblanchard** [paceholder/nodeeditor#392]
Hello,

I have an embedded widget in a custom node, containing a layout and a frame with text.
When initializing the widgets, the frame size is OK (fully inside node):
![image](https://github.com/paceholder/nodeeditor/assets/63931618/db395e97-82c0-456d-bfdb-9fdb267de9e6)

But when updating the text of the label (after clicking on it, through code in click event), the size is KO (label is out of node perimeter):
![image](https://github.com/paceholder/nodeeditor/assets/63931618/628264d1-b1cb-45d3-8ec7-c5123820fab2)

Thank you for your help..

**Comment by Trzeth** [comment]
Hi yvanblanchard, i figure it out and find quite easy.

If you're using deafult DataFlowGraphModel and DataFlowGraphicsScene like me, everything is almost ok.
This work is based on main brach commit 5465ddc91f1b30823c5fc3def93138cbec4c9394


What you need to do is:
1. add a Q_SIGNALS in DataFlowGraphModel.hpp named `void embeddedWidgetSizeUpdated(NodeId const);`
2. connect this in DataFlowGraphModel.cpp in `DataFlowGraphModel::addNode(QString const nodeType)` function with `connect(model.get(),&NodeDelegateModel::embeddedWidgetSizeUpdated,this,[newId, this](){Q_EMIT embeddedWidgetSizeUpdated(newId);});`
3. PS: You will see lots of connect method there, you can't miss it. ;)
4. last step is connect this in DataFlowGraphicsScene.cpp in the constructor with `connect(&_graphModel,&DataFlowGraphModel::embeddedWidgetSizeUpdated,[this](NodeId const nodeId){ onNodeUpdated(nodeId); });`
5. now you can use `this->embeddedWidgetSizeUpdated();` in your DataModel

**Comment by QiuYilin** [comment]
DataFlowGraphModel.hpp
```
Q_SIGNALS:
     void inPortDataWasSet(NodeId const,PortType const,PortIndex const);
     +void outPortDataUpdated(NodeId const)
```
DataFlowGraphModel.cpp
```
void DataFlowGraphModel::onOutPortDataUpdated(NodeId const nodeId)
{
      +Q_EMIT outPortDataUpdated(nodeId);
      ...
}
```
DataFlowGraphicsScene.cpp

```
+connect(&_graphModel,
             +&DataFlowGraphModel::outPortDataUpdated,
             +[this](NodeId const nodeId) { onNodeUpdated(nodeId); });
```

**Comment by yvanblanchard** [comment]
Thank you !
