### ISSUE TITLE
Missing or incorrect inputs text

### ISSUE THREAD

**Issue by yvanblanchard** [paceholder/nodeeditor#407]
Hello,

Is it possible to display text in the node UI, for incorrect/missing inputs ?
I saw some images/screenshots in past issues with it, but thelast v3 branch code does not integrate it. 
Is it planned ? or is there another way to manage it (and how) ? don't see anything in the documentation for this.

![image](https://github.com/paceholder/nodeeditor/assets/63931618/4b307609-bffb-40a7-bcb5-ab3d2b34ec17)

Thank you.

**Comment by paceholder** [comment]
My idea was to implement some pop-up or tooltip-slyled notifications next to the "incorrect" port but I simplit did not have time to properly implement it. Sorry
