### ISSUE TITLE
Embedded widget with wrong size when content has changed

### ISSUE THREAD

**Issue by yvanblanchard** [paceholder/nodeeditor#408]
Hello,

I have a node with an embedded widget (QtLabel).
This Label widget contained a quite long text, and after updating the flow graph, this node was updated and text was shorter.
Problem is that the lable widget kept its previous size, instead of being resized as expected.
The node (container) of this widget was correctly resized (smaller), but not the widget child..

Before:
![image](https://github.com/paceholder/nodeeditor/assets/63931618/2478660c-0d69-4cd0-bbee-3cb92958b706)

After:
![image](https://github.com/paceholder/nodeeditor/assets/63931618/41604c54-0a51-444a-9037-abb824f943db)

Any idea ?

**Comment by mariusalexander** [comment]
Can you try to use a QLayout to manage the size of the label?
```cpp
QWidget* embeddedWidget() {
    auto* widget = new QWidget;
    auto* lay = new QVBoxLayout; // or QHBoxLayout
    auto* label = new QLabel; // your label
    lay->addWidget(label);
    widget->setLayout(lay);
    return widget;
}
```

**Comment by yvanblanchard** [comment]
@mariusalexander 
thank you, but I had already used layout for my embedded widget.
it seems like this issue is possibly related to a Qt bug: @121

**Comment by yvanblanchard** [comment]
when using 'embeddedWidgetSizeUpdated' in eventFilter of the widget (Qlabel orother), it works fine!
