### ISSUE TITLE
resizable_images Demo的双击事件无法捕获

### ISSUE THREAD

**Issue by aaaaalun** [paceholder/nodeeditor#420]
代码中使用的是单击的事件，我换成双击的事情一直无法捕获，查看代码也没有找到其他地方截取了这个双击事件，不知道是什么原因。

**Comment by aaaaalun** [comment]
已解决，双击事件在eventFilter中会先触发MouseButtonPress然后才是MouseButtonDblClick，所以外层不能直接return false。

**Comment by Z-XQ** [comment]
> 已解决，双击事件在eventFilter中会先触发MouseButtonPress然后才是MouseButtonDblClick，所以外层不能直接return false。

感谢！有帮助
