### ISSUE TITLE
Some usage issues.

### ISSUE THREAD

**Issue by timpc0526** [paceholder/nodeeditor#424]
Hello,
I'm working within a project environment consisting of VS2022, Qt5.15.2, and Win10. I have several questions regarding the project:

1. When compiling the .dll files, both the release and debug versions are named QtNodes.dll. Is there a method to distinguish between them, perhaps as QtNodes.dll for release and QtNodesd.dll for debug?
2. In debug mode, executing the simple_graph_model example in my project results in an error at LINE:996 debug_heap.cpp. This error doesn't occur in release mode. Specifically, the error appears at the end of the traverseGraphAndPopulateGraphicsObjects function in BasicGraphicsScene. 
3. What are the distinctions between using NodeDelegateModel and AbstractGraphModel to create a Node? Additionally, the scenes used, DataFlowGraphicsScene for NodeDelegateModel and BasicGraphicsScene for AbstractGraphModel, differ. They are implemented differently across various examples.

In accordance with the project's requirements:
1. We need to utilize external buttons to add Nodes, with the option to also use a built-in menu for this purpose.
2. Each added Node requires a user-defined unique ID.
3. The input interface should support multiple types of input.
4. Is there a recommended approach to generate data representing the current connection status?

I look forward to your response. Thank you.

**Comment by paceholder** [comment]
1. See the property in the root CMakeLists.txt `BUILD_DEBUG_POSTFIX_D`
2. Can't immediately understand what might have gone wrong. Maybe I corrupted some heap memory.
3. `AbstractGraphModel`  serves well when you write some general-purpose graph rendering application, not necessarily related to data propagation. Then you might need to wrap your graph into this model and feed to the scene. See example `graph`. https://qtnodes.readthedocs.io/en/master/overview.html

If you are interesting in data-flow approach or data propagation from one node to another, you could use a more granulated approach by defining the smaller models for each specific node type. You don't see the whole graph model in this case as this is handled by the framework. See example `calculator`. https://qtnodes.readthedocs.io/en/master/features.html#data-propagation
