### ISSUE TITLE
reading code

### ISSUE THREAD

**Issue by w1005444804** [paceholder/nodeeditor#425]
Thank you very much for sharing this project, Could you please offer some advice or guidance on how to approach reading your code?

**Comment by paceholder** [comment]
Sory for a very delayed repsonse.

1. Read the docs and understand the code structure. https://qtnodes.readthedocs.io/en/master/
2. Look through the examples, understand how the bricks are layed together.
3. Define the item you want to check/modify/understand better, go to the appropriate class in the source code.
4. If something not clear, ask more specific question.
