### ISSUE TITLE
How to pull request if I have lots of commit ?

### ISSUE THREAD

**Issue by bansan85** [paceholder/nodeeditor#429]
@paceholder 

I worked on nodeeditor half an year ago. I fixed lots of tiny thing, I added a (buggy) QML wrapper but it's a good start. I also added some examples. I also changed the algorithm to draw line connection to avoid overlapping with boxes.

How do you like I send you MR ? One for each commit ? A big MR with lots of commit and you review them one by one ?

**Comment by paceholder** [comment]
Hello!

Sorry for mu belated response -- many things to do besides this project.
I'd prefer splitting the PRs by topic. 

Regards,
Dimitry

**Comment by bansan85** [comment]
OK. After few hours, I successfully isolated the qml part. I also added few example.

It's difficult for me to split every topic because I made changes in one time without thinking about merging them properly.

**Comment by alesof** [comment]
Hi @bansan85! I'm interested in using nodeeditor with qml so i pulled your branch to test it out. I think there is an issue with how the events are forwarded, as left click drag on the items is not working. Do you have a solution? I managed to make it work on right click drag.

Moreover, to make your branch work I had to modify some things (e.g. the button inside the main.qml without import of Controls; the anchors to an undefined id). Therefore, I think that you'd want to update it before the PR. I can provide what i had to modify to make the example work, if you'd like.

Thank you again for this!

**Comment by bansan85** [comment]
I no longer work on improving nodeeditor. But I will do my best effort so that PR #449 will be merged.

If you want to contribute to this PR, maybe you could clone my repository (https://github.com/bansan85/nodeeditor/) and work on branch add_qml. Then create a PR on my repository and finally, PR #449 will be updated.

I'm also fine if you want to take part of my PR and create another PR with smaller commits.

The only remaining bug I noticed in uml is that zooming zooms on the mouse position only if the nodeeditor is at (0, 0) position. This is why I added a button at (0, 0) position in my uml example.
