### ISSUE TITLE
__debugbread() occurs when running the example in debug mode using vs2022

### ISSUE THREAD

**Issue by BCC168** [paceholder/nodeeditor#435]
I use vs2022 to compile the examples. Works fine in release mode, but in debug mode I get a __debugbreak() error when right clicking.
 It seems that an out-of-bounds conflict occurs during QArrayDataPointer destruction when it try to `free(d)`, which ends up in ntdll.dll. If this behavior is safe, please tell me how to skip this warning in visual studio.

**Comment by paceholder** [comment]
I am not able to check it on windows with vs2022 at the moment. Maybe someone else has noticed such a behavior?

**Comment by paceholder** [comment]
Did you try to use any other Qt version?
