### ISSUE TITLE
crashed when running the calculator

### ISSUE THREAD

**Issue by CuberFan** [paceholder/nodeeditor#442]
in the calculator, there is a crash when I connect the node "NumberSoure" and node “Addition”

QT  6.7.2
Windows 10
MSVC 2019

![20240919154147](https://github.com/user-attachments/assets/da0af931-77e7-434c-ab74-e744918393da)

**Comment by chateauferret** [comment]
That looks pretty similar to #441 which I raised yesterday. [https://github.com/paceholder/nodeeditor/issues/441](https://github.com/paceholder/nodeeditor/issues/441
)

**Comment by CuberFan** [comment]
> That looks pretty similar to #441 which I raised yesterday. #441

thanks!

**Comment by paceholder** [comment]
I think this is fixed now. Please reopen if the problem persists
