### ISSUE TITLE
ComboBox as Embedded Widget not expanding

### ISSUE THREAD

**Issue by kelvinkrycek** [paceholder/nodeeditor#448]
Hi,
first I want to thank you for this great library! 
I am using it for a few days now and encountered an issue when using a QComboBox as an embedded widget. 

I am using this code (`MPatternPrefabModel` inherits from `NodeDelegateModel`);
```
QWidget* MPatternPrefabModel::embeddedWidget()
{
	if (!mWidget) {
		QListWidget* listModel = new QListWidget();
		listModel->addItems({ "Pattern 1", "Pattern 2", "Pattern 3" });
		QComboBox* comboBox = new QComboBox(mWidget);
		comboBox->setModel(listModel->model());
		comboBox->setView(listModel);
		connect(comboBox, &QComboBox::activated, this, &MPatternPrefabModel::onComboBoxActivated);	
		mWidget = comboBox;
	}
	return mWidget;
}
```

I am using Qt 6.7.2, build on Windows with Visual Studio 2022

The combo box is shown in the widget but when I click on it, it is not expanding to show the options. Instead, the cursor is turning into a hand (like the one use see when draging the entire workspace around).
Is there some usage flaw on my side. 
Thank you!

**Comment by paceholder** [comment]
Your sample code looks a bit overcomplicated.

How about this one:

```cpp
 15     QComboBox* comboBox = new QComboBox(nullptr);                                 
 16     comboBox->addItems({ "Pattern 1", "Pattern 2", "Pattern 3" });                
```

I hacked the "text" example and basically copy-pasted an extisting mode with replacing the orignial widget with `QComboBox`. I've put the data into the widget in a delegate model's contstructor and returned widget from ` QWidget *embeddedWidget() override { return _comboBox; } `

And it works!
![image](https://github.com/user-attachments/assets/79b48668-e4f3-4bb6-9e86-b8399f6000b8)

Here is the patch with respect to the current `HEAD`
[combo-box.patch](https://github.com/user-attachments/files/17790832/combo-box.patch)

**Comment by wuxianggujun** [comment]
> Hi,  你好， first I want to thank you for this great library!首先我要感谢你们创建了这个伟大的图书馆！ I am using it for a few days now and encountered an issue when using a QComboBox as an embedded widget.我已经使用了几天了，在使用 QComboBox 作为嵌入小部件时遇到了一个问题。
> 
> I am using this code (`MPatternPrefabModel` inherits from `NodeDelegateModel`);我正在使用这段代码（ `MPatternPrefabModel` 继承自 `NodeDelegateModel` ）；
> 
> ```
> QWidget* MPatternPrefabModel::embeddedWidget()
> {
> 	if (!mWidget) {
> 		QListWidget* listModel = new QListWidget();
> 		listModel->addItems({ "Pattern 1", "Pattern 2", "Pattern 3" });
> 		QComboBox* comboBox = new QComboBox(mWidget);
> 		comboBox->setModel(listModel->model());
> 		comboBox->setView(listModel);
> 		connect(comboBox, &QComboBox::activated, this, &MPatternPrefabModel::onComboBoxActivated);	
> 		mWidget = comboBox;
> 	}
> 	return mWidget;
> }
> ```
> 
> I am using Qt 6.7.2, build on Windows with Visual Studio 2022我正在使用 Qt 6.7.2，在 Windows 上使用 Visual Studio 2022 进行构建
> 
> The combo box is shown in the widget but when I click on it, it is not expanding to show the options. Instead, the cursor is turning into a hand (like the one use see when draging the entire workspace around).组合框显示在小部件中，但当我点击它时，它并没有展开显示选项。相反，光标变成了一只手（就像拖动整个工作区时看到的那样）。 Is there some usage flaw on my side.我这边是否存在一些使用缺陷？ Thank you!  谢谢你！

#if defined(Q_OS_WINDOWS)
    // 修复Qt6在Windows 11上QComboBox在QGraphicsProxyWidget中无法显示下拉菜单的问题
    // 参考: https://forum.qt.io/topic/158614/qcombobox-fails-to-display-dropdown-when-placed-in-qgraphicsview-via-qgraphicsproxywidget
    QApplication::setStyle(QStyleFactory::create("windowsvista"));
#endif
