### ISSUE TITLE
Marquee Selection

### ISSUE THREAD

**Issue by russelltg** [paceholder/nodeeditor#47]
It would be nice to be able to select nodes in a marquee selection.

Left-click is currently used for moving the viewport + nodes, so maybe right click for marquee?

**Comment by paceholder** [comment]
Do you mean something like this?
![image](https://cloud.githubusercontent.com/assets/322952/22243686/ac353096-e228-11e6-87db-e311fdad4497.png)

Shift + LMB = rectangle selection
Ctrl + LMB = add objects one by one to the selection group

**Comment by russelltg** [comment]
Aah yes, didn't see that :).

Thanks
