### ISSUE TITLE
Showcase section in readme

### ISSUE THREAD

**Issue by russelltg** [paceholder/nodeeditor#48]
I was thinking it might be nice (for you and your users) to have a "showcase" section in the readme showcasing some of the projects that use your library. 

It would show that it is actually well used and that it is chosen by other developers.

What do you think? If you're OK with it I'll file a PR adding chigraph to it...

**Comment by paceholder** [comment]
Good idea. I am afraid the only live project I can mention is your chigraph library. I've got many *stars* but did not see anything serious except the couple of student projects.
