### ISSUE TITLE
Output duplication

### ISSUE THREAD

**Issue by jcelerier** [paceholder/nodeeditor#5]
From the examples, it seems that there cannot be two outbound edges coming from the same port of a node. Is this a hard limitation on the library or could it be easily lifted ? (Or I just couldn't manage to do it).

Thanks !
##

**Comment by jamesdwebb** [comment]
I was wondering the same thing. The first thing I tried to do in the calculator example was make a squaring design where a single number source would drive both inputs of a multiplier. It would be very nice if this was made easily possible - it feels great to use otherwise.

**Comment by paceholder** [comment]
For now it is not possible but I will rework the library to allow it.

**Comment by v0q** [comment]
I will leave it to @paceholder to come up with an official implementation for this (great tool btw!). I needed this for my own project and modified the editor to give me this functionality and can be found on my fork at https://github.com/v0q/nodeeditor

**Comment by paceholder** [comment]
Hi @v0q,

thanks for sharing the code. I took time ideas from your solution. Btw, it would be very interesting to see some screenshots of your project.

Duplicated outgoing connections are pushed to master.

**Comment by jcelerier** [comment]
Thanks !!!



-------
Jean-Michaël Celerier
http://www.jcelerier.name

**Comment by v0q** [comment]
Just gonna leave this here but here's a screenshot of my project (for an university assignment). Basically it allows the user to model using Signed Distance Fields in real-time. The node editor is being used to generate a graph of the scene that's then parsed to a shader
![sdf](https://cloud.githubusercontent.com/assets/1763369/20793688/2e5eefdc-b7c0-11e6-8092-061413b835ca.png)

**Comment by paceholder** [comment]
@v0q, that is interesting! Thanks for the screenshot. The first example of the "live" library application.

**Comment by paceholder** [comment]
@v0q, is it possible to access the sources?

**Comment by v0q** [comment]
Just gonna post it here as you asked it @paceholder, I had a chat with the guy I'm working on the assignment with and we decided to make the repo public. You can find the repo here: https://github.com/v0q/CollaborativeResearchProject

Most up-to-date version is probably on the dev-teemu branch. Do note that we're still using the older version of the node editor as we already modified it quite a bit when you got the update out. Forgive me for any spaghetti code, been focusing more on getting the features we want working.

Thanks for the great node editor, your effort has made our lives so much easier.

**Comment by paceholder** [comment]
My laptop does not support GLSL 4.10, I will try to compile it at work tomorrow. Thanks for sharing the code! (is it my chance to understand shaders?)

**Comment by v0q** [comment]
The shaders don't really have anything 4.10 specific (at least shouldn't have) so I think you can just make the version number lower. The shaders are basically for rendering signed distance fields so nothing too fancy. So I think you should be fine :)
