### ISSUE TITLE
Crash on Load of a new node graph

### ISSUE THREAD

**Issue by mtbrobotanist** [paceholder/nodeeditor#54]
Hi, awesome product with one small issue:

The Node editor calculator example crashes when loading a second .flow file after an initial load. loading a new graph in its place causes an memory access violation whenever FlowScene::load() calls _connections.clear(); 

I'm using Visual Studio 2015 Community on Windows 10 with Qt 5.7.

**Comment by paceholder** [comment]
Hi! Thanks for reporting an issue, I will review it in the nearest time.
