### ISSUE TITLE
Suggestion: downgrade to c++11 anf Qt 5.2

### ISSUE THREAD

**Issue by facontidavide** [paceholder/nodeeditor#58]
Hi,

First of all, thanks for this very nice piece of software.
I am currently working on Ubuntu 14.04 (I am stacked to that version for several reasons).

I had to do some changes to downgrade the code. Not many indeed.
Would you be interested to "downgrade" your requirements to allow a broader availability of your library?

I can send you a Pull request, if you agree.

Cheers

Davide

**Comment by paceholder** [comment]
Hi David,

thanks for your appreciation. I think there is nothing bad in downgrading the version of Qt.
As I remember, I just put the current version from my machine to the cmake config.

Please, make sure that the code is compilable and all examples work as they should.

Best,
Dmitry

**Comment by paceholder** [comment]
Sorry, just noticed the C++11 -- it will not work right away. I use `std::make_unique` that came to the standard just with C++14. You would need to instrument the code with some `#ifdef` conditions and provide the implementation with C++11 (`std::unique_ptr<ClassName>(new ClassName(params))`).
