### ISSUE TITLE
Support for OSX

### ISSUE THREAD

**Issue by Schizo** [paceholder/nodeeditor#72]
Is OSX not supported or wasn't it just tested yet?

**Comment by paceholder** [comment]
Hi!

I used to build and run it once on OSX. (I installed Qt and Cmake with `homebrew`).
Besides, I know there were some users of this library working on Mac computers.

I don't own a Mac, that is why I can't test it regularly. But most probably it will work as expected.
Let me know if something goes wrong and I'll fix it.

Best,
Dmitry

**Comment by paceholder** [comment]
I will add a continuous integration build on osx.

**Comment by Schizo** [comment]
Sounds good, I will try to compile it on OSX with clang.

**Comment by Schizo** [comment]
I've successfully build it, looks good!

![image](https://cloud.githubusercontent.com/assets/38006/24156781/721090e2-0e4f-11e7-8aea-d97e55298656.png)

**Comment by russelltg** [comment]
I run a CI build for my project on OSX, works great

**Comment by paceholder** [comment]
I need to look at your config

**Comment by russelltg** [comment]
Here's my [.travis.yml](https://github.com/chigraph/chigraph/blob/master/.travis.yml), my [install.sh](https://github.com/chigraph/chigraph/blob/master/.travis/install.sh), which installs dependencies, and my [build.sh](https://github.com/chigraph/chigraph/blob/master/.travis/build.sh) which compiles it.
