### ISSUE TITLE
Graphics glitch when validation state changes

### ISSUE THREAD

**Issue by russelltg** [paceholder/nodeeditor#75]
![bug](https://cloud.githubusercontent.com/assets/7105082/24225094/3a8e85cc-0f24-11e7-8d7f-bca433f83a19.gif)

Pretty small bug, but it looks a little funky. 

Easy workaround of just dragging on one of the nodes.

**Comment by paceholder** [comment]
I don't like this jumpy nodes and large red notification area. It breaks the elegance and simplicity of the framework. I will find the time on the weekend and re-do it properly (with tool-tips and highlighted connection sockets).

**Comment by russelltg** [comment]
I agree, the jumpy nodes can be really annoying (I had several cases where I found a node behind another node because the validation state changed). plus there are definitely some graphical bugs.

**Comment by russelltg** [comment]
For me it'd be nice to be able to click on the error tooltip after it comes up and click on links in the error message.

That'd be useful because I'm looking to add "quickfixes" to errors, so people can click a button to fix it immediately for simple errors.
