### ISSUE TITLE
Bounding boxes don't match node visuals

### ISSUE THREAD

**Issue by russelltg** [paceholder/nodeeditor#77]
When selecting nodes, it seems to be that the "hitbox" for the nodes are way bigger than the visuals for the node:

![boundingbox](https://cloud.githubusercontent.com/assets/7105082/24279376/131c9380-100f-11e7-9e53-7907848994d6.gif)

This is especially annoying when trying to select a connection that connects to the same node (yeah that's actually useful in chigraph, think looping):
![boundingbox2](https://cloud.githubusercontent.com/assets/7105082/24279486/b55aa7f4-100f-11e7-889f-ff64fe57654f.gif)

**Comment by paceholder** [comment]
That's true. The node's shadow belongs to the bounding box as well
