### ISSUE TITLE
Programmatic node creation ?

### ISSUE THREAD

**Issue by jcelerier** [paceholder/nodeeditor#80]
Hello,

I have the following case in my software: the main structure I manipulate is a [time-line](https://raw.githubusercontent.com/OSSIA/i-score/master/Documentation/iscore.png)

Now, for some of the relationships I have on the time-line, I'd like to get a visual representation with nodeeditor (that the user wouldn't really be able to change). But the examples seem to imply that creating nodes should only be done from the GUI.

What would be the best way to create nodes from code, layout them in the scene, add connections? thanks

**Comment by paceholder** [comment]
Hi

we basically do such a programmatic node creation after the user clicks the item in a menu.

All you need to do is to call
`Node& FlowScene::createNode(std::unique_ptr<NodeDataModel> && dataModel)`

After obtaining the reference to `Node` it is possible to get `NodeGraphicsObject` and set the position in the scene.

Does it answer your question?

**Comment by jcelerier** [comment]
I did not see that FlowScene was in the public api, sorry

**Comment by paceholder** [comment]
No problem. It is not the correct "public library API". In the `include` folder I have stupid stubs like:
`#include "../../../NodeGeometry.hpp"

The usage of such an "API" is not possible without having the sources. I.e. it is not possible now to work with a binary lib + headers.

Once I tried to separate the "public" headers and "private" headers but it resulted it a serious refactoring that was postponed. 

Regards
Dmitry
