### ISSUE TITLE
Add Qwidget to each port?

### ISSUE THREAD

**Issue by ragundo** [paceholder/nodeeditor#81]
Hi. First of all, thanks for this fantastic library!

I've recently started to use it, but , for my needs, I would need to show some data in each port
![blueprint](https://cloud.githubusercontent.com/assets/9405614/24632356/21e73d1c-18c4-11e7-93d6-777059d36a31.png)
This is from Unreal Blueprint editor, but you can get the idea, show some data between the port name and the port connection...

Is it possible to do something like this?. I'm looking at the source code, but some clues from you would be great.

Thanks in advance

**Comment by russelltg** [comment]
I'd definitely be able to use this :+1:

**Comment by paceholder** [comment]
Hi thanks for your appreciation.

There is a way to add one QWidget in the central part of the Node. It is up to you how complicated this central widget is constructed. I would add several children widgets with predefined vertical stride. It is possible to make children widgets visible or invisible on demand (everything is happening inside the user-defined model).

Have a look at the example `images` -- it shows how to return a central QWidget from a model.

[A couple of guys have implemented](https://github.com/v0q/CollaborativeResearchProject) the whole 3D editor where they had "vector components" node with three number-editors. The Qt Node Editor was slightly modified but the concept is the same as proposed above.

In the picture you can see (hopefully) nodes with three editors.
![3D Editor](https://raw.githubusercontent.com/v0q/CollaborativeResearchProject/master/Examples/1.png)

Let me know if that helps.

Regards,
Dmitry

**Comment by ragundo** [comment]
I see.
Create a central widget with children widgets "aligned" to each port. I would need to figure out how to calculate the point relative to the node origin where draw each children in order to be aligned with the ports.

Thanks

**Comment by infamicstudios** [comment]
Does anybody have an example implementation of this? Would the best place to do this be during node painting or would this have to be implemented on a per node bases?
