### ISSUE TITLE
Locking the psoition of Nodes and Connections

### ISSUE THREAD

**Issue by facontidavide** [paceholder/nodeeditor#85]
I need to implement a feature to lock/unlock the position of Connections and Nodes (and prevent deleting). 

I can work on it myself and send you a PR, it you agree with this enhancement.

- In which class would you add these methods? Node, NodeGeometry or  NodeGraphicObject? 

For the records, I would prefer the latter, but it is just personal taste. This is your code, you decide ;)

**Comment by russelltg** [comment]
This would be useful for me. I'm thinking maybe a "capability" bitfield, which you can set specific bits (move, delete, connect, etc)

**Comment by facontidavide** [comment]
I will prepare a preliminary PR to start a more focused discussion, then

**Comment by paceholder** [comment]
Good idea, thank you. As it seems to be related solely to the Node's visual representation, I would put it `NodeState`

**Comment by facontidavide** [comment]
converted to PR #90
