### ISSUE TITLE
Graphical issues when embedded widget is too big

### ISSUE THREAD

**Issue by ArnaudGallardo** [paceholder/nodeeditor#93]
<img width="464" alt="screen shot 2017-05-18 at 5 46 10 pm" src="https://cloud.githubusercontent.com/assets/10815172/26211241/6a64e318-3bf2-11e7-8352-6ce3db7749ea.png">

I know the lib is not really intended to deal with multiple inputs but I'm trying to do it anyway. The problem is only graphical, inputs works great.

I tried to set the node height manually but with no success. Is there like a max height setting somewhere?

Thanks for the lib!

**Comment by paceholder** [comment]
Hi! Thanks for submitting the bug. It it strange that the hight is limited. I will have a look

**Comment by paceholder** [comment]
Could you please share the code where you construct the model's widget?
I can't reproduce the issue.

![image](https://cloud.githubusercontent.com/assets/322952/26221047/65cd5eac-3c15-11e7-9cd3-a2ba87531892.png)

**Comment by ArnaudGallardo** [comment]
The specific node I showed on my first post was dynamically generated, so there is no specific code I can give you to duplicate except the whole project. I thought that maybe my _"dynamic node creation system"_ might be the one messing up with the graphics so I added the **NaiveDataModel** from the **connection_colors** example to my project and changed the "embeddedWidget" to this piece of code :
```
QWidget *
  embeddedWidget() override { //return nullptr;
    QFormLayout * layout = new QFormLayout;
    for (int i = 0; i < 15; i++)
    {
        QLineEdit * le = new QLineEdit;
        QString s = QString::number(i);
        layout->addRow(s,le);
    }
    QWidget * widget = new QWidget;
    widget->setLayout(layout);
    widget->setMaximumSize(widget->sizeHint());
    return widget;
  }
```

Here are the results :
![tests](https://cloud.githubusercontent.com/assets/10815172/26237071/d9640fe2-3c73-11e7-8cb9-8600ea0a1b5f.png)

I tried different styling options to be sure that it has nothing to do with it.

Here is another example with more rows :
![screen shot 2017-05-19 at 9 20 29 am](https://cloud.githubusercontent.com/assets/10815172/26237233/9991bc74-3c74-11e7-9229-8f82eee658c0.png)

Also, I'm doing this to set **nodeeditor** as the central widget of my main project, maybe it's where the problem comes from... :
```
NodeEditor::NodeEditor()
{
    ::setStyle();

    scene = new FlowScene(registerDataModels());
    this->view = new FlowView(scene);
}

QWidget *
NodeEditor::getWidget()
{
    return ((QGraphicsView *)(this->view));
}
//NodeEditor is one of my class.
```

**Comment by ArnaudGallardo** [comment]
Alright, that's not a bug, that's just me.
When I first wrote my function I took your **calculator/NumberSourceDataModel.cpp** as example where the widget creation is :

```
_lineEdit->setValidator(new QDoubleValidator());

_lineEdit->setMaximumSize(_lineEdit->sizeHint());

connect(_lineEdit, &QLineEdit::textChanged,
          this, &NumberSourceDataModel::onTextEdited);

_lineEdit->setText("0.0");
```

So I also used `setMaximumSize` to create my widget and got a wrong result.

I changed it to `setMinimumSize` and got : 
![screen shot 2017-05-19 at 9 44 25 am](https://cloud.githubusercontent.com/assets/10815172/26238119/0296867a-3c78-11e7-82f3-d25412c79a84.png)

So I'm finally using :
```
widget->setMinimumHeight(widget->sizeHint().height());
widget->setMaximumWidth(widget->sizeHint().width());
```
And now the result is fine :
![screen shot 2017-05-19 at 9 43 34 am](https://cloud.githubusercontent.com/assets/10815172/26238158/34975b9a-3c78-11e7-8360-0e2cdd9a305b.png)

**Comment by paceholder** [comment]
I guess one does not need to set the size explicitly. From what I know it works just fine with the automatically defined size. Anyway, nice that it finally works.
