### ISSUE TITLE
Resizing Nodes can turn them invisible

### ISSUE THREAD

**Issue by schumacb** [paceholder/nodeeditor#96]
![invisiblenodes](https://cloud.githubusercontent.com/assets/389108/26679706/90e21bfc-46d6-11e7-958a-b089cd323e8f.gif)

This was tested on an xubuntu14.04 machine.

When a node is rendered invisible the console is spammed with messages from the QPainter about being not active. E.g.:

`QPainter::end: Painter not active, aborted`

**Comment by paceholder** [comment]
I found the bug  and will fix it soon.
