### ISSUE TITLE
Access the topology of a graph

### ISSUE THREAD

**Issue by Quincunx271** [paceholder/nodeeditor#97]
Given a graph that the user constructed, I need to be able to access the topology of the graph.

Currently, it almost seems possible with `FlowScene::nodes()` and `FlowScene::connections()`, but although `Connection` is defined through its header, `Node` is not. `Node` is merely forward declared. If **Node.hpp** was visible or `#include`'d somewhere, it would work.

**Comment by russelltg** [comment]
Agreed. On my fork I actually export Node and include `<../src/Node.hpp>`. It's definitely a needed feature.

**Comment by paceholder** [comment]
@russelltg  Could you please make a pull-request?
