### ISSUE TITLE
Replace std::cout with QMessageLogger or other logging

### ISSUE THREAD

**Issue by Quincunx271** [paceholder/nodeeditor#98]
Currently, there are 4 places which stream to `std::cout` (one of them is commented out):

* **src/ConnectionGraphicsObject.cpp**:  `std::cout << "Remove ConnectionGraphicsObject from scene" << std::endl;`
* **src/Properties.cpp**:  `//std::cout << "Properties already have a value with the name '"`
* **src/Connection.cpp**:  `std::cout << "Connection destructor" << std::endl;`
* **src/Node.cpp**:  `std::cout << "Node destructor" << std::endl;`

These clutter stdout. Either they should be removed, or replaced with the [QMessageLogger](http://doc.qt.io/qt-5/qmessagelogger.html) system.

For example:

```c++
Node::
~Node()
{
  qCInfo(QLoggingCategory("QtNodes")) << "Node destructor";
}
```

This way, users of the library could customize the output of the log messages if necessary. The exact way of initializing the [`QLoggingCategory`](http://doc.qt.io/qt-5/qloggingcategory.html) might have to be different, but a quick test shows that this seems to work with [`qInstallMessageHandler()`](http://doc.qt.io/qt-5/qtglobal.html#qInstallMessageHandler)

**Comment by paceholder** [comment]
Hi! Nice point. 

These messages are actually left-overs from the developing phase. I can remove them.
